copy J:\Apps\Products\AccuGlobe\LocalUnits\build\01AlleganTwp\IntlFt\Parcels.shp S:\Secure\Units\AlleganTwp\LIS\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\02CascoTwp\IntlFt\Parcels.shp S:\Secure\Units\CascoTwp\LIS\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\03CheshireTwp\IntlFt\Parcels.shp S:\Secure\Units\CheshireTwp\LIS\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\04ClydeTwp\IntlFt\Parcels.shp S:\Secure\Units\ClydeTwp\LIS\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\05DorrTwp\IntlFt\Parcels.shp S:\Secure\Units\DorrTwp\LIS\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\06FillmoreTwp\IntlFt\Parcels.shp S:\Secure\Units\FillmoreTwp\LIS\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\07GangesTwp\IntlFt\Parcels.shp S:\Secure\Units\GangesTwp\LIS\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\08GunPlainTwp\IntlFt\Parcels.shp S:\Secure\Units\GunPlainTwp\LIS\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\09HeathTwp\IntlFt\Parcels.shp S:\Secure\Units\HeathTwp\LIS\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\10HopkinsTwp\IntlFt\Parcels.shp S:\Secure\Units\HopkinsTwp\LIS\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\11LaketownTwp\IntlFt\Parcels.shp S:\Secure\Units\LaketownTwp\LIS\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\12LeeTwp\IntlFt\Parcels.shp S:\Secure\Units\LeeTwp\LIS\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\13LeightonTwp\IntlFt\Parcels.shp S:\Secure\Units\LeightonTwp\LIS\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\14ManliusTwp\IntlFt\Parcels.shp S:\Secure\Units\ManliusTwp\LIS\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\15MartinTwp\IntlFt\Parcels.shp S:\Secure\Units\MartinTwp\LIS\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\16MontereyTwp\IntlFt\Parcels.shp S:\Secure\Units\MontereyTwp\LIS\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\17OtsegoTwp\IntlFt\Parcels.shp S:\Secure\Units\OtsegoTwp\LIS\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\18OveriselTwp\IntlFt\Parcels.shp S:\Secure\Units\OveriselTwp\LIS\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\19SalemTwp\IntlFt\Parcels.shp S:\Secure\Units\SalemTwp\LIS\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\20SaugatuckTwp\IntlFt\Parcels.shp S:\Secure\Units\SaugatuckTwp\LIS\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\21TrowbridgeTwp\IntlFt\Parcels.shp S:\Secure\Units\TrowbridgeTwp\LIS\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\22ValleyTwp\IntlFt\Parcels.shp S:\Secure\Units\ValleyTwp\LIS\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\23WatsonTwp\IntlFt\Parcels.shp S:\Secure\Units\WatsonTwp\LIS\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\24WaylandTwp\IntlFt\Parcels.shp S:\Secure\Units\WaylandTwp\LIS\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\42MartinVillage\IntlFt\Parcels.shp S:\Secure\Units\MartinVillage\LIS\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\44HopkinsVillage\IntlFt\Parcels.shp S:\Secure\Units\HopkinsVillage\LIS\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\51AlleganCity\IntlFt\Parcels.shp S:\Secure\Units\AlleganCity\LIS\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\52FennvilleCity\IntlFt\Parcels.shp S:\Secure\Units\FennvilleCity\LIS\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\54OtsegoCity\IntlFt\Parcels.shp S:\Secure\Units\OtsegoCity\LIS\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\55PlainwellCity\IntlFt\Parcels.shp S:\Secure\Units\PlainwellCity\LIS\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\56WaylandCity\IntlFt\Parcels.shp S:\Secure\Units\WaylandCity\LIS\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\57SaugatuckCity\IntlFt\Parcels.shp S:\Secure\Units\SaugatuckCity\LIS\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\59DouglasCity\IntlFt\Parcels.shp S:\Secure\Units\DouglasCity\LIS\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\01AlleganTwp\IntlFt\Parcels.dbf S:\Secure\Units\AlleganTwp\LIS\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\02CascoTwp\IntlFt\Parcels.dbf S:\Secure\Units\CascoTwp\LIS\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\03CheshireTwp\IntlFt\Parcels.dbf S:\Secure\Units\CheshireTwp\LIS\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\04ClydeTwp\IntlFt\Parcels.dbf S:\Secure\Units\ClydeTwp\LIS\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\05DorrTwp\IntlFt\Parcels.dbf S:\Secure\Units\DorrTwp\LIS\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\06FillmoreTwp\IntlFt\Parcels.dbf S:\Secure\Units\FillmoreTwp\LIS\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\07GangesTwp\IntlFt\Parcels.dbf S:\Secure\Units\GangesTwp\LIS\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\08GunPlainTwp\IntlFt\Parcels.dbf S:\Secure\Units\GunPlainTwp\LIS\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\09HeathTwp\IntlFt\Parcels.dbf S:\Secure\Units\HeathTwp\LIS\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\10HopkinsTwp\IntlFt\Parcels.dbf S:\Secure\Units\HopkinsTwp\LIS\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\11LaketownTwp\IntlFt\Parcels.dbf S:\Secure\Units\LaketownTwp\LIS\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\12LeeTwp\IntlFt\Parcels.dbf S:\Secure\Units\LeeTwp\LIS\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\13LeightonTwp\IntlFt\Parcels.dbf S:\Secure\Units\LeightonTwp\LIS\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\14ManliusTwp\IntlFt\Parcels.dbf S:\Secure\Units\ManliusTwp\LIS\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\15MartinTwp\IntlFt\Parcels.dbf S:\Secure\Units\MartinTwp\LIS\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\16MontereyTwp\IntlFt\Parcels.dbf S:\Secure\Units\MontereyTwp\LIS\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\17OtsegoTwp\IntlFt\Parcels.dbf S:\Secure\Units\OtsegoTwp\LIS\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\18OveriselTwp\IntlFt\Parcels.dbf S:\Secure\Units\OveriselTwp\LIS\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\19SalemTwp\IntlFt\Parcels.dbf S:\Secure\Units\SalemTwp\LIS\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\20SaugatuckTwp\IntlFt\Parcels.dbf S:\Secure\Units\SaugatuckTwp\LIS\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\21TrowbridgeTwp\IntlFt\Parcels.dbf S:\Secure\Units\TrowbridgeTwp\LIS\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\22ValleyTwp\IntlFt\Parcels.dbf S:\Secure\Units\ValleyTwp\LIS\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\23WatsonTwp\IntlFt\Parcels.dbf S:\Secure\Units\WatsonTwp\LIS\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\24WaylandTwp\IntlFt\Parcels.dbf S:\Secure\Units\WaylandTwp\LIS\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\42MartinVillage\IntlFt\Parcels.dbf S:\Secure\Units\MartinVillage\LIS\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\44HopkinsVillage\IntlFt\Parcels.dbf S:\Secure\Units\HopkinsVillage\LIS\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\51AlleganCity\IntlFt\Parcels.dbf S:\Secure\Units\AlleganCity\LIS\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\52FennvilleCity\IntlFt\Parcels.dbf S:\Secure\Units\FennvilleCity\LIS\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\54OtsegoCity\IntlFt\Parcels.dbf S:\Secure\Units\OtsegoCity\LIS\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\55PlainwellCity\IntlFt\Parcels.dbf S:\Secure\Units\PlainwellCity\LIS\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\56WaylandCity\IntlFt\Parcels.dbf S:\Secure\Units\WaylandCity\LIS\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\57SaugatuckCity\IntlFt\Parcels.dbf S:\Secure\Units\SaugatuckCity\LIS\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\59DouglasCity\IntlFt\Parcels.dbf S:\Secure\Units\DouglasCity\LIS\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\01AlleganTwp\IntlFt\Parcels.shx S:\Secure\Units\AlleganTwp\LIS\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\02CascoTwp\IntlFt\Parcels.shx S:\Secure\Units\CascoTwp\LIS\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\03CheshireTwp\IntlFt\Parcels.shx S:\Secure\Units\CheshireTwp\LIS\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\04ClydeTwp\IntlFt\Parcels.shx S:\Secure\Units\ClydeTwp\LIS\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\05DorrTwp\IntlFt\Parcels.shx S:\Secure\Units\DorrTwp\LIS\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\06FillmoreTwp\IntlFt\Parcels.shx S:\Secure\Units\FillmoreTwp\LIS\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\07GangesTwp\IntlFt\Parcels.shx S:\Secure\Units\GangesTwp\LIS\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\08GunPlainTwp\IntlFt\Parcels.shx S:\Secure\Units\GunPlainTwp\LIS\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\09HeathTwp\IntlFt\Parcels.shx S:\Secure\Units\HeathTwp\LIS\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\10HopkinsTwp\IntlFt\Parcels.shx S:\Secure\Units\HopkinsTwp\LIS\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\11LaketownTwp\IntlFt\Parcels.shx S:\Secure\Units\LaketownTwp\LIS\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\12LeeTwp\IntlFt\Parcels.shx S:\Secure\Units\LeeTwp\LIS\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\13LeightonTwp\IntlFt\Parcels.shx S:\Secure\Units\LeightonTwp\LIS\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\14ManliusTwp\IntlFt\Parcels.shx S:\Secure\Units\ManliusTwp\LIS\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\15MartinTwp\IntlFt\Parcels.shx S:\Secure\Units\MartinTwp\LIS\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\16MontereyTwp\IntlFt\Parcels.shx S:\Secure\Units\MontereyTwp\LIS\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\17OtsegoTwp\IntlFt\Parcels.shx S:\Secure\Units\OtsegoTwp\LIS\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\18OveriselTwp\IntlFt\Parcels.shx S:\Secure\Units\OveriselTwp\LIS\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\19SalemTwp\IntlFt\Parcels.shx S:\Secure\Units\SalemTwp\LIS\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\20SaugatuckTwp\IntlFt\Parcels.shx S:\Secure\Units\SaugatuckTwp\LIS\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\21TrowbridgeTwp\IntlFt\Parcels.shx S:\Secure\Units\TrowbridgeTwp\LIS\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\22ValleyTwp\IntlFt\Parcels.shx S:\Secure\Units\ValleyTwp\LIS\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\23WatsonTwp\IntlFt\Parcels.shx S:\Secure\Units\WatsonTwp\LIS\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\24WaylandTwp\IntlFt\Parcels.shx S:\Secure\Units\WaylandTwp\LIS\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\42MartinVillage\IntlFt\Parcels.shx S:\Secure\Units\MartinVillage\LIS\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\44HopkinsVillage\IntlFt\Parcels.shx S:\Secure\Units\HopkinsVillage\LIS\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\51AlleganCity\IntlFt\Parcels.shx S:\Secure\Units\AlleganCity\LIS\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\52FennvilleCity\IntlFt\Parcels.shx S:\Secure\Units\FennvilleCity\LIS\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\54OtsegoCity\IntlFt\Parcels.shx S:\Secure\Units\OtsegoCity\LIS\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\55PlainwellCity\IntlFt\Parcels.shx S:\Secure\Units\PlainwellCity\LIS\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\56WaylandCity\IntlFt\Parcels.shx S:\Secure\Units\WaylandCity\LIS\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\57SaugatuckCity\IntlFt\Parcels.shx S:\Secure\Units\SaugatuckCity\LIS\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\59DouglasCity\IntlFt\Parcels.shx S:\Secure\Units\DouglasCity\LIS\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\01AlleganTwp\IntlFt\Parcels.prj S:\Secure\Units\AlleganTwp\LIS\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\02CascoTwp\IntlFt\Parcels.prj S:\Secure\Units\CascoTwp\LIS\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\03CheshireTwp\IntlFt\Parcels.prj S:\Secure\Units\CheshireTwp\LIS\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\04ClydeTwp\IntlFt\Parcels.prj S:\Secure\Units\ClydeTwp\LIS\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\05DorrTwp\IntlFt\Parcels.prj S:\Secure\Units\DorrTwp\LIS\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\06FillmoreTwp\IntlFt\Parcels.prj S:\Secure\Units\FillmoreTwp\LIS\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\07GangesTwp\IntlFt\Parcels.prj S:\Secure\Units\GangesTwp\LIS\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\08GunPlainTwp\IntlFt\Parcels.prj S:\Secure\Units\GunPlainTwp\LIS\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\09HeathTwp\IntlFt\Parcels.prj S:\Secure\Units\HeathTwp\LIS\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\10HopkinsTwp\IntlFt\Parcels.prj S:\Secure\Units\HopkinsTwp\LIS\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\11LaketownTwp\IntlFt\Parcels.prj S:\Secure\Units\LaketownTwp\LIS\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\12LeeTwp\IntlFt\Parcels.prj S:\Secure\Units\LeeTwp\LIS\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\13LeightonTwp\IntlFt\Parcels.prj S:\Secure\Units\LeightonTwp\LIS\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\14ManliusTwp\IntlFt\Parcels.prj S:\Secure\Units\ManliusTwp\LIS\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\15MartinTwp\IntlFt\Parcels.prj S:\Secure\Units\MartinTwp\LIS\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\16MontereyTwp\IntlFt\Parcels.prj S:\Secure\Units\MontereyTwp\LIS\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\17OtsegoTwp\IntlFt\Parcels.prj S:\Secure\Units\OtsegoTwp\LIS\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\18OveriselTwp\IntlFt\Parcels.prj S:\Secure\Units\OveriselTwp\LIS\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\19SalemTwp\IntlFt\Parcels.prj S:\Secure\Units\SalemTwp\LIS\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\20SaugatuckTwp\IntlFt\Parcels.prj S:\Secure\Units\SaugatuckTwp\LIS\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\21TrowbridgeTwp\IntlFt\Parcels.prj S:\Secure\Units\TrowbridgeTwp\LIS\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\22ValleyTwp\IntlFt\Parcels.prj S:\Secure\Units\ValleyTwp\LIS\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\23WatsonTwp\IntlFt\Parcels.prj S:\Secure\Units\WatsonTwp\LIS\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\24WaylandTwp\IntlFt\Parcels.prj S:\Secure\Units\WaylandTwp\LIS\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\42MartinVillage\IntlFt\Parcels.prj S:\Secure\Units\MartinVillage\LIS\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\44HopkinsVillage\IntlFt\Parcels.prj S:\Secure\Units\HopkinsVillage\LIS\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\51AlleganCity\IntlFt\Parcels.prj S:\Secure\Units\AlleganCity\LIS\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\52FennvilleCity\IntlFt\Parcels.prj S:\Secure\Units\FennvilleCity\LIS\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\54OtsegoCity\IntlFt\Parcels.prj S:\Secure\Units\OtsegoCity\LIS\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\55PlainwellCity\IntlFt\Parcels.prj S:\Secure\Units\PlainwellCity\LIS\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\56WaylandCity\IntlFt\Parcels.prj S:\Secure\Units\WaylandCity\LIS\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\57SaugatuckCity\IntlFt\Parcels.prj S:\Secure\Units\SaugatuckCity\LIS\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\59DouglasCity\IntlFt\Parcels.prj S:\Secure\Units\DouglasCity\LIS\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\01AlleganTwp\IntlFt\Parcels.cpg S:\Secure\Units\AlleganTwp\LIS\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\02CascoTwp\IntlFt\Parcels.cpg S:\Secure\Units\CascoTwp\LIS\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\03CheshireTwp\IntlFt\Parcels.cpg S:\Secure\Units\CheshireTwp\LIS\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\04ClydeTwp\IntlFt\Parcels.cpg S:\Secure\Units\ClydeTwp\LIS\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\05DorrTwp\IntlFt\Parcels.cpg S:\Secure\Units\DorrTwp\LIS\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\06FillmoreTwp\IntlFt\Parcels.cpg S:\Secure\Units\FillmoreTwp\LIS\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\07GangesTwp\IntlFt\Parcels.cpg S:\Secure\Units\GangesTwp\LIS\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\08GunPlainTwp\IntlFt\Parcels.cpg S:\Secure\Units\GunPlainTwp\LIS\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\09HeathTwp\IntlFt\Parcels.cpg S:\Secure\Units\HeathTwp\LIS\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\10HopkinsTwp\IntlFt\Parcels.cpg S:\Secure\Units\HopkinsTwp\LIS\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\11LaketownTwp\IntlFt\Parcels.cpg S:\Secure\Units\LaketownTwp\LIS\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\12LeeTwp\IntlFt\Parcels.cpg S:\Secure\Units\LeeTwp\LIS\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\13LeightonTwp\IntlFt\Parcels.cpg S:\Secure\Units\LeightonTwp\LIS\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\14ManliusTwp\IntlFt\Parcels.cpg S:\Secure\Units\ManliusTwp\LIS\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\15MartinTwp\IntlFt\Parcels.cpg S:\Secure\Units\MartinTwp\LIS\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\16MontereyTwp\IntlFt\Parcels.cpg S:\Secure\Units\MontereyTwp\LIS\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\17OtsegoTwp\IntlFt\Parcels.cpg S:\Secure\Units\OtsegoTwp\LIS\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\18OveriselTwp\IntlFt\Parcels.cpg S:\Secure\Units\OveriselTwp\LIS\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\19SalemTwp\IntlFt\Parcels.cpg S:\Secure\Units\SalemTwp\LIS\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\20SaugatuckTwp\IntlFt\Parcels.cpg S:\Secure\Units\SaugatuckTwp\LIS\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\21TrowbridgeTwp\IntlFt\Parcels.cpg S:\Secure\Units\TrowbridgeTwp\LIS\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\22ValleyTwp\IntlFt\Parcels.cpg S:\Secure\Units\ValleyTwp\LIS\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\23WatsonTwp\IntlFt\Parcels.cpg S:\Secure\Units\WatsonTwp\LIS\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\24WaylandTwp\IntlFt\Parcels.cpg S:\Secure\Units\WaylandTwp\LIS\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\42MartinVillage\IntlFt\Parcels.cpg S:\Secure\Units\MartinVillage\LIS\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\44HopkinsVillage\IntlFt\Parcels.cpg S:\Secure\Units\HopkinsVillage\LIS\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\51AlleganCity\IntlFt\Parcels.cpg S:\Secure\Units\AlleganCity\LIS\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\52FennvilleCity\IntlFt\Parcels.cpg S:\Secure\Units\FennvilleCity\LIS\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\54OtsegoCity\IntlFt\Parcels.cpg S:\Secure\Units\OtsegoCity\LIS\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\55PlainwellCity\IntlFt\Parcels.cpg S:\Secure\Units\PlainwellCity\LIS\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\56WaylandCity\IntlFt\Parcels.cpg S:\Secure\Units\WaylandCity\LIS\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\57SaugatuckCity\IntlFt\Parcels.cpg S:\Secure\Units\SaugatuckCity\LIS\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\59DouglasCity\IntlFt\Parcels.cpg S:\Secure\Units\DouglasCity\LIS\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\01AlleganTwp\IntlFt\Parcels.sbn S:\Secure\Units\AlleganTwp\LIS\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\02CascoTwp\IntlFt\Parcels.sbn S:\Secure\Units\CascoTwp\LIS\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\03CheshireTwp\IntlFt\Parcels.sbn S:\Secure\Units\CheshireTwp\LIS\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\04ClydeTwp\IntlFt\Parcels.sbn S:\Secure\Units\ClydeTwp\LIS\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\05DorrTwp\IntlFt\Parcels.sbn S:\Secure\Units\DorrTwp\LIS\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\06FillmoreTwp\IntlFt\Parcels.sbn S:\Secure\Units\FillmoreTwp\LIS\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\07GangesTwp\IntlFt\Parcels.sbn S:\Secure\Units\GangesTwp\LIS\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\08GunPlainTwp\IntlFt\Parcels.sbn S:\Secure\Units\GunPlainTwp\LIS\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\09HeathTwp\IntlFt\Parcels.sbn S:\Secure\Units\HeathTwp\LIS\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\10HopkinsTwp\IntlFt\Parcels.sbn S:\Secure\Units\HopkinsTwp\LIS\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\11LaketownTwp\IntlFt\Parcels.sbn S:\Secure\Units\LaketownTwp\LIS\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\12LeeTwp\IntlFt\Parcels.sbn S:\Secure\Units\LeeTwp\LIS\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\13LeightonTwp\IntlFt\Parcels.sbn S:\Secure\Units\LeightonTwp\LIS\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\14ManliusTwp\IntlFt\Parcels.sbn S:\Secure\Units\ManliusTwp\LIS\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\15MartinTwp\IntlFt\Parcels.sbn S:\Secure\Units\MartinTwp\LIS\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\16MontereyTwp\IntlFt\Parcels.sbn S:\Secure\Units\MontereyTwp\LIS\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\17OtsegoTwp\IntlFt\Parcels.sbn S:\Secure\Units\OtsegoTwp\LIS\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\18OveriselTwp\IntlFt\Parcels.sbn S:\Secure\Units\OveriselTwp\LIS\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\19SalemTwp\IntlFt\Parcels.sbn S:\Secure\Units\SalemTwp\LIS\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\20SaugatuckTwp\IntlFt\Parcels.sbn S:\Secure\Units\SaugatuckTwp\LIS\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\21TrowbridgeTwp\IntlFt\Parcels.sbn S:\Secure\Units\TrowbridgeTwp\LIS\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\22ValleyTwp\IntlFt\Parcels.sbn S:\Secure\Units\ValleyTwp\LIS\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\23WatsonTwp\IntlFt\Parcels.sbn S:\Secure\Units\WatsonTwp\LIS\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\24WaylandTwp\IntlFt\Parcels.sbn S:\Secure\Units\WaylandTwp\LIS\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\42MartinVillage\IntlFt\Parcels.sbn S:\Secure\Units\MartinVillage\LIS\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\44HopkinsVillage\IntlFt\Parcels.sbn S:\Secure\Units\HopkinsVillage\LIS\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\51AlleganCity\IntlFt\Parcels.sbn S:\Secure\Units\AlleganCity\LIS\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\52FennvilleCity\IntlFt\Parcels.sbn S:\Secure\Units\FennvilleCity\LIS\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\54OtsegoCity\IntlFt\Parcels.sbn S:\Secure\Units\OtsegoCity\LIS\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\55PlainwellCity\IntlFt\Parcels.sbn S:\Secure\Units\PlainwellCity\LIS\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\56WaylandCity\IntlFt\Parcels.sbn S:\Secure\Units\WaylandCity\LIS\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\57SaugatuckCity\IntlFt\Parcels.sbn S:\Secure\Units\SaugatuckCity\LIS\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\59DouglasCity\IntlFt\Parcels.sbn S:\Secure\Units\DouglasCity\LIS\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\01AlleganTwp\IntlFt\Parcels.shp.xml S:\Secure\Units\AlleganTwp\LIS\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\02CascoTwp\IntlFt\Parcels.shp.xml S:\Secure\Units\CascoTwp\LIS\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\03CheshireTwp\IntlFt\Parcels.shp.xml S:\Secure\Units\CheshireTwp\LIS\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\04ClydeTwp\IntlFt\Parcels.shp.xml S:\Secure\Units\ClydeTwp\LIS\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\05DorrTwp\IntlFt\Parcels.shp.xml S:\Secure\Units\DorrTwp\LIS\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\06FillmoreTwp\IntlFt\Parcels.shp.xml S:\Secure\Units\FillmoreTwp\LIS\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\07GangesTwp\IntlFt\Parcels.shp.xml S:\Secure\Units\GangesTwp\LIS\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\08GunPlainTwp\IntlFt\Parcels.shp.xml S:\Secure\Units\GunPlainTwp\LIS\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\09HeathTwp\IntlFt\Parcels.shp.xml S:\Secure\Units\HeathTwp\LIS\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\10HopkinsTwp\IntlFt\Parcels.shp.xml S:\Secure\Units\HopkinsTwp\LIS\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\11LaketownTwp\IntlFt\Parcels.shp.xml S:\Secure\Units\LaketownTwp\LIS\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\12LeeTwp\IntlFt\Parcels.shp.xml S:\Secure\Units\LeeTwp\LIS\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\13LeightonTwp\IntlFt\Parcels.shp.xml S:\Secure\Units\LeightonTwp\LIS\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\14ManliusTwp\IntlFt\Parcels.shp.xml S:\Secure\Units\ManliusTwp\LIS\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\15MartinTwp\IntlFt\Parcels.shp.xml S:\Secure\Units\MartinTwp\LIS\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\16MontereyTwp\IntlFt\Parcels.shp.xml S:\Secure\Units\MontereyTwp\LIS\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\17OtsegoTwp\IntlFt\Parcels.shp.xml S:\Secure\Units\OtsegoTwp\LIS\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\18OveriselTwp\IntlFt\Parcels.shp.xml S:\Secure\Units\OveriselTwp\LIS\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\19SalemTwp\IntlFt\Parcels.shp.xml S:\Secure\Units\SalemTwp\LIS\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\20SaugatuckTwp\IntlFt\Parcels.shp.xml S:\Secure\Units\SaugatuckTwp\LIS\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\21TrowbridgeTwp\IntlFt\Parcels.shp.xml S:\Secure\Units\TrowbridgeTwp\LIS\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\22ValleyTwp\IntlFt\Parcels.shp.xml S:\Secure\Units\ValleyTwp\LIS\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\23WatsonTwp\IntlFt\Parcels.shp.xml S:\Secure\Units\WatsonTwp\LIS\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\24WaylandTwp\IntlFt\Parcels.shp.xml S:\Secure\Units\WaylandTwp\LIS\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\42MartinVillage\IntlFt\Parcels.shp.xml S:\Secure\Units\MartinVillage\LIS\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\44HopkinsVillage\IntlFt\Parcels.shp.xml S:\Secure\Units\HopkinsVillage\LIS\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\51AlleganCity\IntlFt\Parcels.shp.xml S:\Secure\Units\AlleganCity\LIS\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\52FennvilleCity\IntlFt\Parcels.shp.xml S:\Secure\Units\FennvilleCity\LIS\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\54OtsegoCity\IntlFt\Parcels.shp.xml S:\Secure\Units\OtsegoCity\LIS\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\55PlainwellCity\IntlFt\Parcels.shp.xml S:\Secure\Units\PlainwellCity\LIS\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\56WaylandCity\IntlFt\Parcels.shp.xml S:\Secure\Units\WaylandCity\LIS\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\57SaugatuckCity\IntlFt\Parcels.shp.xml S:\Secure\Units\SaugatuckCity\LIS\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\59DouglasCity\IntlFt\Parcels.shp.xml S:\Secure\Units\DouglasCity\LIS\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\01AlleganTwp\IntlFt\Parcels.sbx S:\Secure\Units\AlleganTwp\LIS\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\02CascoTwp\IntlFt\Parcels.sbx S:\Secure\Units\CascoTwp\LIS\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\03CheshireTwp\IntlFt\Parcels.sbx S:\Secure\Units\CheshireTwp\LIS\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\04ClydeTwp\IntlFt\Parcels.sbx S:\Secure\Units\ClydeTwp\LIS\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\05DorrTwp\IntlFt\Parcels.sbx S:\Secure\Units\DorrTwp\LIS\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\06FillmoreTwp\IntlFt\Parcels.sbx S:\Secure\Units\FillmoreTwp\LIS\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\07GangesTwp\IntlFt\Parcels.sbx S:\Secure\Units\GangesTwp\LIS\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\08GunPlainTwp\IntlFt\Parcels.sbx S:\Secure\Units\GunPlainTwp\LIS\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\09HeathTwp\IntlFt\Parcels.sbx S:\Secure\Units\HeathTwp\LIS\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\10HopkinsTwp\IntlFt\Parcels.sbx S:\Secure\Units\HopkinsTwp\LIS\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\11LaketownTwp\IntlFt\Parcels.sbx S:\Secure\Units\LaketownTwp\LIS\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\12LeeTwp\IntlFt\Parcels.sbx S:\Secure\Units\LeeTwp\LIS\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\13LeightonTwp\IntlFt\Parcels.sbx S:\Secure\Units\LeightonTwp\LIS\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\14ManliusTwp\IntlFt\Parcels.sbx S:\Secure\Units\ManliusTwp\LIS\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\15MartinTwp\IntlFt\Parcels.sbx S:\Secure\Units\MartinTwp\LIS\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\16MontereyTwp\IntlFt\Parcels.sbx S:\Secure\Units\MontereyTwp\LIS\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\17OtsegoTwp\IntlFt\Parcels.sbx S:\Secure\Units\OtsegoTwp\LIS\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\18OveriselTwp\IntlFt\Parcels.sbx S:\Secure\Units\OveriselTwp\LIS\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\19SalemTwp\IntlFt\Parcels.sbx S:\Secure\Units\SalemTwp\LIS\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\20SaugatuckTwp\IntlFt\Parcels.sbx S:\Secure\Units\SaugatuckTwp\LIS\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\21TrowbridgeTwp\IntlFt\Parcels.sbx S:\Secure\Units\TrowbridgeTwp\LIS\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\22ValleyTwp\IntlFt\Parcels.sbx S:\Secure\Units\ValleyTwp\LIS\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\23WatsonTwp\IntlFt\Parcels.sbx S:\Secure\Units\WatsonTwp\LIS\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\24WaylandTwp\IntlFt\Parcels.sbx S:\Secure\Units\WaylandTwp\LIS\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\42MartinVillage\IntlFt\Parcels.sbx S:\Secure\Units\MartinVillage\LIS\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\44HopkinsVillage\IntlFt\Parcels.sbx S:\Secure\Units\HopkinsVillage\LIS\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\51AlleganCity\IntlFt\Parcels.sbx S:\Secure\Units\AlleganCity\LIS\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\52FennvilleCity\IntlFt\Parcels.sbx S:\Secure\Units\FennvilleCity\LIS\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\54OtsegoCity\IntlFt\Parcels.sbx S:\Secure\Units\OtsegoCity\LIS\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\55PlainwellCity\IntlFt\Parcels.sbx S:\Secure\Units\PlainwellCity\LIS\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\56WaylandCity\IntlFt\Parcels.sbx S:\Secure\Units\WaylandCity\LIS\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\57SaugatuckCity\IntlFt\Parcels.sbx S:\Secure\Units\SaugatuckCity\LIS\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\59DouglasCity\IntlFt\Parcels.sbx S:\Secure\Units\DouglasCity\LIS\IntlFt\Parcels.sbx
