copy J:\Apps\Products\AccuGlobe\LocalUnits\build\01AlleganTwp\IntlFt\ParcelsPlus.shp S:\Secure\Units\AlleganTwp\LIS\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\02CascoTwp\IntlFt\ParcelsPlus.shp S:\Secure\Units\CascoTwp\LIS\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\03CheshireTwp\IntlFt\ParcelsPlus.shp S:\Secure\Units\CheshireTwp\LIS\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\04ClydeTwp\IntlFt\ParcelsPlus.shp S:\Secure\Units\ClydeTwp\LIS\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\05DorrTwp\IntlFt\ParcelsPlus.shp S:\Secure\Units\DorrTwp\LIS\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\06FillmoreTwp\IntlFt\ParcelsPlus.shp S:\Secure\Units\FillmoreTwp\LIS\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\07GangesTwp\IntlFt\ParcelsPlus.shp S:\Secure\Units\GangesTwp\LIS\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\08GunPlainTwp\IntlFt\ParcelsPlus.shp S:\Secure\Units\GunPlainTwp\LIS\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\09HeathTwp\IntlFt\ParcelsPlus.shp S:\Secure\Units\HeathTwp\LIS\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\10HopkinsTwp\IntlFt\ParcelsPlus.shp S:\Secure\Units\HopkinsTwp\LIS\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\11LaketownTwp\IntlFt\ParcelsPlus.shp S:\Secure\Units\LaketownTwp\LIS\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\12LeeTwp\IntlFt\ParcelsPlus.shp S:\Secure\Units\LeeTwp\LIS\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\13LeightonTwp\IntlFt\ParcelsPlus.shp S:\Secure\Units\LeightonTwp\LIS\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\14ManliusTwp\IntlFt\ParcelsPlus.shp S:\Secure\Units\ManliusTwp\LIS\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\15MartinTwp\IntlFt\ParcelsPlus.shp S:\Secure\Units\MartinTwp\LIS\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\16MontereyTwp\IntlFt\ParcelsPlus.shp S:\Secure\Units\MontereyTwp\LIS\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\17OtsegoTwp\IntlFt\ParcelsPlus.shp S:\Secure\Units\OtsegoTwp\LIS\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\18OveriselTwp\IntlFt\ParcelsPlus.shp S:\Secure\Units\OveriselTwp\LIS\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\19SalemTwp\IntlFt\ParcelsPlus.shp S:\Secure\Units\SalemTwp\LIS\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\20SaugatuckTwp\IntlFt\ParcelsPlus.shp S:\Secure\Units\SaugatuckTwp\LIS\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\21TrowbridgeTwp\IntlFt\ParcelsPlus.shp S:\Secure\Units\TrowbridgeTwp\LIS\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\22ValleyTwp\IntlFt\ParcelsPlus.shp S:\Secure\Units\ValleyTwp\LIS\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\23WatsonTwp\IntlFt\ParcelsPlus.shp S:\Secure\Units\WatsonTwp\LIS\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\24WaylandTwp\IntlFt\ParcelsPlus.shp S:\Secure\Units\WaylandTwp\LIS\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\42MartinVillage\IntlFt\ParcelsPlus.shp S:\Secure\Units\MartinVillage\LIS\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\44HopkinsVillage\IntlFt\ParcelsPlus.shp S:\Secure\Units\HopkinsVillage\LIS\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\51AlleganCity\IntlFt\ParcelsPlus.shp S:\Secure\Units\AlleganCity\LIS\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\52FennvilleCity\IntlFt\ParcelsPlus.shp S:\Secure\Units\FennvilleCity\LIS\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\54OtsegoCity\IntlFt\ParcelsPlus.shp S:\Secure\Units\OtsegoCity\LIS\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\55PlainwellCity\IntlFt\ParcelsPlus.shp S:\Secure\Units\PlainwellCity\LIS\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\56WaylandCity\IntlFt\ParcelsPlus.shp S:\Secure\Units\WaylandCity\LIS\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\57SaugatuckCity\IntlFt\ParcelsPlus.shp S:\Secure\Units\SaugatuckCity\LIS\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\59DouglasCity\IntlFt\ParcelsPlus.shp S:\Secure\Units\DouglasCity\LIS\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\01AlleganTwp\IntlFt\ParcelsPlus.dbf S:\Secure\Units\AlleganTwp\LIS\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\02CascoTwp\IntlFt\ParcelsPlus.dbf S:\Secure\Units\CascoTwp\LIS\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\03CheshireTwp\IntlFt\ParcelsPlus.dbf S:\Secure\Units\CheshireTwp\LIS\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\04ClydeTwp\IntlFt\ParcelsPlus.dbf S:\Secure\Units\ClydeTwp\LIS\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\05DorrTwp\IntlFt\ParcelsPlus.dbf S:\Secure\Units\DorrTwp\LIS\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\06FillmoreTwp\IntlFt\ParcelsPlus.dbf S:\Secure\Units\FillmoreTwp\LIS\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\07GangesTwp\IntlFt\ParcelsPlus.dbf S:\Secure\Units\GangesTwp\LIS\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\08GunPlainTwp\IntlFt\ParcelsPlus.dbf S:\Secure\Units\GunPlainTwp\LIS\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\09HeathTwp\IntlFt\ParcelsPlus.dbf S:\Secure\Units\HeathTwp\LIS\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\10HopkinsTwp\IntlFt\ParcelsPlus.dbf S:\Secure\Units\HopkinsTwp\LIS\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\11LaketownTwp\IntlFt\ParcelsPlus.dbf S:\Secure\Units\LaketownTwp\LIS\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\12LeeTwp\IntlFt\ParcelsPlus.dbf S:\Secure\Units\LeeTwp\LIS\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\13LeightonTwp\IntlFt\ParcelsPlus.dbf S:\Secure\Units\LeightonTwp\LIS\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\14ManliusTwp\IntlFt\ParcelsPlus.dbf S:\Secure\Units\ManliusTwp\LIS\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\15MartinTwp\IntlFt\ParcelsPlus.dbf S:\Secure\Units\MartinTwp\LIS\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\16MontereyTwp\IntlFt\ParcelsPlus.dbf S:\Secure\Units\MontereyTwp\LIS\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\17OtsegoTwp\IntlFt\ParcelsPlus.dbf S:\Secure\Units\OtsegoTwp\LIS\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\18OveriselTwp\IntlFt\ParcelsPlus.dbf S:\Secure\Units\OveriselTwp\LIS\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\19SalemTwp\IntlFt\ParcelsPlus.dbf S:\Secure\Units\SalemTwp\LIS\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\20SaugatuckTwp\IntlFt\ParcelsPlus.dbf S:\Secure\Units\SaugatuckTwp\LIS\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\21TrowbridgeTwp\IntlFt\ParcelsPlus.dbf S:\Secure\Units\TrowbridgeTwp\LIS\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\22ValleyTwp\IntlFt\ParcelsPlus.dbf S:\Secure\Units\ValleyTwp\LIS\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\23WatsonTwp\IntlFt\ParcelsPlus.dbf S:\Secure\Units\WatsonTwp\LIS\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\24WaylandTwp\IntlFt\ParcelsPlus.dbf S:\Secure\Units\WaylandTwp\LIS\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\42MartinVillage\IntlFt\ParcelsPlus.dbf S:\Secure\Units\MartinVillage\LIS\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\44HopkinsVillage\IntlFt\ParcelsPlus.dbf S:\Secure\Units\HopkinsVillage\LIS\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\51AlleganCity\IntlFt\ParcelsPlus.dbf S:\Secure\Units\AlleganCity\LIS\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\52FennvilleCity\IntlFt\ParcelsPlus.dbf S:\Secure\Units\FennvilleCity\LIS\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\54OtsegoCity\IntlFt\ParcelsPlus.dbf S:\Secure\Units\OtsegoCity\LIS\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\55PlainwellCity\IntlFt\ParcelsPlus.dbf S:\Secure\Units\PlainwellCity\LIS\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\56WaylandCity\IntlFt\ParcelsPlus.dbf S:\Secure\Units\WaylandCity\LIS\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\57SaugatuckCity\IntlFt\ParcelsPlus.dbf S:\Secure\Units\SaugatuckCity\LIS\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\59DouglasCity\IntlFt\ParcelsPlus.dbf S:\Secure\Units\DouglasCity\LIS\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\01AlleganTwp\IntlFt\ParcelsPlus.shx S:\Secure\Units\AlleganTwp\LIS\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\02CascoTwp\IntlFt\ParcelsPlus.shx S:\Secure\Units\CascoTwp\LIS\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\03CheshireTwp\IntlFt\ParcelsPlus.shx S:\Secure\Units\CheshireTwp\LIS\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\04ClydeTwp\IntlFt\ParcelsPlus.shx S:\Secure\Units\ClydeTwp\LIS\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\05DorrTwp\IntlFt\ParcelsPlus.shx S:\Secure\Units\DorrTwp\LIS\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\06FillmoreTwp\IntlFt\ParcelsPlus.shx S:\Secure\Units\FillmoreTwp\LIS\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\07GangesTwp\IntlFt\ParcelsPlus.shx S:\Secure\Units\GangesTwp\LIS\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\08GunPlainTwp\IntlFt\ParcelsPlus.shx S:\Secure\Units\GunPlainTwp\LIS\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\09HeathTwp\IntlFt\ParcelsPlus.shx S:\Secure\Units\HeathTwp\LIS\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\10HopkinsTwp\IntlFt\ParcelsPlus.shx S:\Secure\Units\HopkinsTwp\LIS\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\11LaketownTwp\IntlFt\ParcelsPlus.shx S:\Secure\Units\LaketownTwp\LIS\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\12LeeTwp\IntlFt\ParcelsPlus.shx S:\Secure\Units\LeeTwp\LIS\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\13LeightonTwp\IntlFt\ParcelsPlus.shx S:\Secure\Units\LeightonTwp\LIS\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\14ManliusTwp\IntlFt\ParcelsPlus.shx S:\Secure\Units\ManliusTwp\LIS\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\15MartinTwp\IntlFt\ParcelsPlus.shx S:\Secure\Units\MartinTwp\LIS\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\16MontereyTwp\IntlFt\ParcelsPlus.shx S:\Secure\Units\MontereyTwp\LIS\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\17OtsegoTwp\IntlFt\ParcelsPlus.shx S:\Secure\Units\OtsegoTwp\LIS\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\18OveriselTwp\IntlFt\ParcelsPlus.shx S:\Secure\Units\OveriselTwp\LIS\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\19SalemTwp\IntlFt\ParcelsPlus.shx S:\Secure\Units\SalemTwp\LIS\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\20SaugatuckTwp\IntlFt\ParcelsPlus.shx S:\Secure\Units\SaugatuckTwp\LIS\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\21TrowbridgeTwp\IntlFt\ParcelsPlus.shx S:\Secure\Units\TrowbridgeTwp\LIS\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\22ValleyTwp\IntlFt\ParcelsPlus.shx S:\Secure\Units\ValleyTwp\LIS\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\23WatsonTwp\IntlFt\ParcelsPlus.shx S:\Secure\Units\WatsonTwp\LIS\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\24WaylandTwp\IntlFt\ParcelsPlus.shx S:\Secure\Units\WaylandTwp\LIS\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\42MartinVillage\IntlFt\ParcelsPlus.shx S:\Secure\Units\MartinVillage\LIS\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\44HopkinsVillage\IntlFt\ParcelsPlus.shx S:\Secure\Units\HopkinsVillage\LIS\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\51AlleganCity\IntlFt\ParcelsPlus.shx S:\Secure\Units\AlleganCity\LIS\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\52FennvilleCity\IntlFt\ParcelsPlus.shx S:\Secure\Units\FennvilleCity\LIS\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\54OtsegoCity\IntlFt\ParcelsPlus.shx S:\Secure\Units\OtsegoCity\LIS\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\55PlainwellCity\IntlFt\ParcelsPlus.shx S:\Secure\Units\PlainwellCity\LIS\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\56WaylandCity\IntlFt\ParcelsPlus.shx S:\Secure\Units\WaylandCity\LIS\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\57SaugatuckCity\IntlFt\ParcelsPlus.shx S:\Secure\Units\SaugatuckCity\LIS\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\59DouglasCity\IntlFt\ParcelsPlus.shx S:\Secure\Units\DouglasCity\LIS\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\01AlleganTwp\IntlFt\ParcelsPlus.prj S:\Secure\Units\AlleganTwp\LIS\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\02CascoTwp\IntlFt\ParcelsPlus.prj S:\Secure\Units\CascoTwp\LIS\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\03CheshireTwp\IntlFt\ParcelsPlus.prj S:\Secure\Units\CheshireTwp\LIS\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\04ClydeTwp\IntlFt\ParcelsPlus.prj S:\Secure\Units\ClydeTwp\LIS\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\05DorrTwp\IntlFt\ParcelsPlus.prj S:\Secure\Units\DorrTwp\LIS\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\06FillmoreTwp\IntlFt\ParcelsPlus.prj S:\Secure\Units\FillmoreTwp\LIS\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\07GangesTwp\IntlFt\ParcelsPlus.prj S:\Secure\Units\GangesTwp\LIS\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\08GunPlainTwp\IntlFt\ParcelsPlus.prj S:\Secure\Units\GunPlainTwp\LIS\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\09HeathTwp\IntlFt\ParcelsPlus.prj S:\Secure\Units\HeathTwp\LIS\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\10HopkinsTwp\IntlFt\ParcelsPlus.prj S:\Secure\Units\HopkinsTwp\LIS\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\11LaketownTwp\IntlFt\ParcelsPlus.prj S:\Secure\Units\LaketownTwp\LIS\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\12LeeTwp\IntlFt\ParcelsPlus.prj S:\Secure\Units\LeeTwp\LIS\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\13LeightonTwp\IntlFt\ParcelsPlus.prj S:\Secure\Units\LeightonTwp\LIS\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\14ManliusTwp\IntlFt\ParcelsPlus.prj S:\Secure\Units\ManliusTwp\LIS\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\15MartinTwp\IntlFt\ParcelsPlus.prj S:\Secure\Units\MartinTwp\LIS\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\16MontereyTwp\IntlFt\ParcelsPlus.prj S:\Secure\Units\MontereyTwp\LIS\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\17OtsegoTwp\IntlFt\ParcelsPlus.prj S:\Secure\Units\OtsegoTwp\LIS\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\18OveriselTwp\IntlFt\ParcelsPlus.prj S:\Secure\Units\OveriselTwp\LIS\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\19SalemTwp\IntlFt\ParcelsPlus.prj S:\Secure\Units\SalemTwp\LIS\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\20SaugatuckTwp\IntlFt\ParcelsPlus.prj S:\Secure\Units\SaugatuckTwp\LIS\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\21TrowbridgeTwp\IntlFt\ParcelsPlus.prj S:\Secure\Units\TrowbridgeTwp\LIS\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\22ValleyTwp\IntlFt\ParcelsPlus.prj S:\Secure\Units\ValleyTwp\LIS\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\23WatsonTwp\IntlFt\ParcelsPlus.prj S:\Secure\Units\WatsonTwp\LIS\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\24WaylandTwp\IntlFt\ParcelsPlus.prj S:\Secure\Units\WaylandTwp\LIS\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\42MartinVillage\IntlFt\ParcelsPlus.prj S:\Secure\Units\MartinVillage\LIS\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\44HopkinsVillage\IntlFt\ParcelsPlus.prj S:\Secure\Units\HopkinsVillage\LIS\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\51AlleganCity\IntlFt\ParcelsPlus.prj S:\Secure\Units\AlleganCity\LIS\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\52FennvilleCity\IntlFt\ParcelsPlus.prj S:\Secure\Units\FennvilleCity\LIS\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\54OtsegoCity\IntlFt\ParcelsPlus.prj S:\Secure\Units\OtsegoCity\LIS\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\55PlainwellCity\IntlFt\ParcelsPlus.prj S:\Secure\Units\PlainwellCity\LIS\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\56WaylandCity\IntlFt\ParcelsPlus.prj S:\Secure\Units\WaylandCity\LIS\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\57SaugatuckCity\IntlFt\ParcelsPlus.prj S:\Secure\Units\SaugatuckCity\LIS\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\59DouglasCity\IntlFt\ParcelsPlus.prj S:\Secure\Units\DouglasCity\LIS\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\01AlleganTwp\IntlFt\ParcelsPlus.cpg S:\Secure\Units\AlleganTwp\LIS\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\02CascoTwp\IntlFt\ParcelsPlus.cpg S:\Secure\Units\CascoTwp\LIS\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\03CheshireTwp\IntlFt\ParcelsPlus.cpg S:\Secure\Units\CheshireTwp\LIS\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\04ClydeTwp\IntlFt\ParcelsPlus.cpg S:\Secure\Units\ClydeTwp\LIS\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\05DorrTwp\IntlFt\ParcelsPlus.cpg S:\Secure\Units\DorrTwp\LIS\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\06FillmoreTwp\IntlFt\ParcelsPlus.cpg S:\Secure\Units\FillmoreTwp\LIS\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\07GangesTwp\IntlFt\ParcelsPlus.cpg S:\Secure\Units\GangesTwp\LIS\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\08GunPlainTwp\IntlFt\ParcelsPlus.cpg S:\Secure\Units\GunPlainTwp\LIS\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\09HeathTwp\IntlFt\ParcelsPlus.cpg S:\Secure\Units\HeathTwp\LIS\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\10HopkinsTwp\IntlFt\ParcelsPlus.cpg S:\Secure\Units\HopkinsTwp\LIS\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\11LaketownTwp\IntlFt\ParcelsPlus.cpg S:\Secure\Units\LaketownTwp\LIS\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\12LeeTwp\IntlFt\ParcelsPlus.cpg S:\Secure\Units\LeeTwp\LIS\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\13LeightonTwp\IntlFt\ParcelsPlus.cpg S:\Secure\Units\LeightonTwp\LIS\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\14ManliusTwp\IntlFt\ParcelsPlus.cpg S:\Secure\Units\ManliusTwp\LIS\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\15MartinTwp\IntlFt\ParcelsPlus.cpg S:\Secure\Units\MartinTwp\LIS\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\16MontereyTwp\IntlFt\ParcelsPlus.cpg S:\Secure\Units\MontereyTwp\LIS\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\17OtsegoTwp\IntlFt\ParcelsPlus.cpg S:\Secure\Units\OtsegoTwp\LIS\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\18OveriselTwp\IntlFt\ParcelsPlus.cpg S:\Secure\Units\OveriselTwp\LIS\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\19SalemTwp\IntlFt\ParcelsPlus.cpg S:\Secure\Units\SalemTwp\LIS\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\20SaugatuckTwp\IntlFt\ParcelsPlus.cpg S:\Secure\Units\SaugatuckTwp\LIS\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\21TrowbridgeTwp\IntlFt\ParcelsPlus.cpg S:\Secure\Units\TrowbridgeTwp\LIS\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\22ValleyTwp\IntlFt\ParcelsPlus.cpg S:\Secure\Units\ValleyTwp\LIS\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\23WatsonTwp\IntlFt\ParcelsPlus.cpg S:\Secure\Units\WatsonTwp\LIS\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\24WaylandTwp\IntlFt\ParcelsPlus.cpg S:\Secure\Units\WaylandTwp\LIS\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\42MartinVillage\IntlFt\ParcelsPlus.cpg S:\Secure\Units\MartinVillage\LIS\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\44HopkinsVillage\IntlFt\ParcelsPlus.cpg S:\Secure\Units\HopkinsVillage\LIS\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\51AlleganCity\IntlFt\ParcelsPlus.cpg S:\Secure\Units\AlleganCity\LIS\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\52FennvilleCity\IntlFt\ParcelsPlus.cpg S:\Secure\Units\FennvilleCity\LIS\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\54OtsegoCity\IntlFt\ParcelsPlus.cpg S:\Secure\Units\OtsegoCity\LIS\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\55PlainwellCity\IntlFt\ParcelsPlus.cpg S:\Secure\Units\PlainwellCity\LIS\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\56WaylandCity\IntlFt\ParcelsPlus.cpg S:\Secure\Units\WaylandCity\LIS\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\57SaugatuckCity\IntlFt\ParcelsPlus.cpg S:\Secure\Units\SaugatuckCity\LIS\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\59DouglasCity\IntlFt\ParcelsPlus.cpg S:\Secure\Units\DouglasCity\LIS\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\01AlleganTwp\IntlFt\ParcelsPlus.sbn S:\Secure\Units\AlleganTwp\LIS\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\02CascoTwp\IntlFt\ParcelsPlus.sbn S:\Secure\Units\CascoTwp\LIS\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\03CheshireTwp\IntlFt\ParcelsPlus.sbn S:\Secure\Units\CheshireTwp\LIS\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\04ClydeTwp\IntlFt\ParcelsPlus.sbn S:\Secure\Units\ClydeTwp\LIS\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\05DorrTwp\IntlFt\ParcelsPlus.sbn S:\Secure\Units\DorrTwp\LIS\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\06FillmoreTwp\IntlFt\ParcelsPlus.sbn S:\Secure\Units\FillmoreTwp\LIS\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\07GangesTwp\IntlFt\ParcelsPlus.sbn S:\Secure\Units\GangesTwp\LIS\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\08GunPlainTwp\IntlFt\ParcelsPlus.sbn S:\Secure\Units\GunPlainTwp\LIS\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\09HeathTwp\IntlFt\ParcelsPlus.sbn S:\Secure\Units\HeathTwp\LIS\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\10HopkinsTwp\IntlFt\ParcelsPlus.sbn S:\Secure\Units\HopkinsTwp\LIS\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\11LaketownTwp\IntlFt\ParcelsPlus.sbn S:\Secure\Units\LaketownTwp\LIS\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\12LeeTwp\IntlFt\ParcelsPlus.sbn S:\Secure\Units\LeeTwp\LIS\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\13LeightonTwp\IntlFt\ParcelsPlus.sbn S:\Secure\Units\LeightonTwp\LIS\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\14ManliusTwp\IntlFt\ParcelsPlus.sbn S:\Secure\Units\ManliusTwp\LIS\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\15MartinTwp\IntlFt\ParcelsPlus.sbn S:\Secure\Units\MartinTwp\LIS\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\16MontereyTwp\IntlFt\ParcelsPlus.sbn S:\Secure\Units\MontereyTwp\LIS\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\17OtsegoTwp\IntlFt\ParcelsPlus.sbn S:\Secure\Units\OtsegoTwp\LIS\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\18OveriselTwp\IntlFt\ParcelsPlus.sbn S:\Secure\Units\OveriselTwp\LIS\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\19SalemTwp\IntlFt\ParcelsPlus.sbn S:\Secure\Units\SalemTwp\LIS\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\20SaugatuckTwp\IntlFt\ParcelsPlus.sbn S:\Secure\Units\SaugatuckTwp\LIS\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\21TrowbridgeTwp\IntlFt\ParcelsPlus.sbn S:\Secure\Units\TrowbridgeTwp\LIS\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\22ValleyTwp\IntlFt\ParcelsPlus.sbn S:\Secure\Units\ValleyTwp\LIS\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\23WatsonTwp\IntlFt\ParcelsPlus.sbn S:\Secure\Units\WatsonTwp\LIS\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\24WaylandTwp\IntlFt\ParcelsPlus.sbn S:\Secure\Units\WaylandTwp\LIS\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\42MartinVillage\IntlFt\ParcelsPlus.sbn S:\Secure\Units\MartinVillage\LIS\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\44HopkinsVillage\IntlFt\ParcelsPlus.sbn S:\Secure\Units\HopkinsVillage\LIS\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\51AlleganCity\IntlFt\ParcelsPlus.sbn S:\Secure\Units\AlleganCity\LIS\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\52FennvilleCity\IntlFt\ParcelsPlus.sbn S:\Secure\Units\FennvilleCity\LIS\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\54OtsegoCity\IntlFt\ParcelsPlus.sbn S:\Secure\Units\OtsegoCity\LIS\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\55PlainwellCity\IntlFt\ParcelsPlus.sbn S:\Secure\Units\PlainwellCity\LIS\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\56WaylandCity\IntlFt\ParcelsPlus.sbn S:\Secure\Units\WaylandCity\LIS\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\57SaugatuckCity\IntlFt\ParcelsPlus.sbn S:\Secure\Units\SaugatuckCity\LIS\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\59DouglasCity\IntlFt\ParcelsPlus.sbn S:\Secure\Units\DouglasCity\LIS\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\01AlleganTwp\IntlFt\ParcelsPlus.shp.xml S:\Secure\Units\AlleganTwp\LIS\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\02CascoTwp\IntlFt\ParcelsPlus.shp.xml S:\Secure\Units\CascoTwp\LIS\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\03CheshireTwp\IntlFt\ParcelsPlus.shp.xml S:\Secure\Units\CheshireTwp\LIS\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\04ClydeTwp\IntlFt\ParcelsPlus.shp.xml S:\Secure\Units\ClydeTwp\LIS\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\05DorrTwp\IntlFt\ParcelsPlus.shp.xml S:\Secure\Units\DorrTwp\LIS\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\06FillmoreTwp\IntlFt\ParcelsPlus.shp.xml S:\Secure\Units\FillmoreTwp\LIS\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\07GangesTwp\IntlFt\ParcelsPlus.shp.xml S:\Secure\Units\GangesTwp\LIS\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\08GunPlainTwp\IntlFt\ParcelsPlus.shp.xml S:\Secure\Units\GunPlainTwp\LIS\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\09HeathTwp\IntlFt\ParcelsPlus.shp.xml S:\Secure\Units\HeathTwp\LIS\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\10HopkinsTwp\IntlFt\ParcelsPlus.shp.xml S:\Secure\Units\HopkinsTwp\LIS\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\11LaketownTwp\IntlFt\ParcelsPlus.shp.xml S:\Secure\Units\LaketownTwp\LIS\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\12LeeTwp\IntlFt\ParcelsPlus.shp.xml S:\Secure\Units\LeeTwp\LIS\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\13LeightonTwp\IntlFt\ParcelsPlus.shp.xml S:\Secure\Units\LeightonTwp\LIS\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\14ManliusTwp\IntlFt\ParcelsPlus.shp.xml S:\Secure\Units\ManliusTwp\LIS\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\15MartinTwp\IntlFt\ParcelsPlus.shp.xml S:\Secure\Units\MartinTwp\LIS\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\16MontereyTwp\IntlFt\ParcelsPlus.shp.xml S:\Secure\Units\MontereyTwp\LIS\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\17OtsegoTwp\IntlFt\ParcelsPlus.shp.xml S:\Secure\Units\OtsegoTwp\LIS\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\18OveriselTwp\IntlFt\ParcelsPlus.shp.xml S:\Secure\Units\OveriselTwp\LIS\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\19SalemTwp\IntlFt\ParcelsPlus.shp.xml S:\Secure\Units\SalemTwp\LIS\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\20SaugatuckTwp\IntlFt\ParcelsPlus.shp.xml S:\Secure\Units\SaugatuckTwp\LIS\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\21TrowbridgeTwp\IntlFt\ParcelsPlus.shp.xml S:\Secure\Units\TrowbridgeTwp\LIS\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\22ValleyTwp\IntlFt\ParcelsPlus.shp.xml S:\Secure\Units\ValleyTwp\LIS\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\23WatsonTwp\IntlFt\ParcelsPlus.shp.xml S:\Secure\Units\WatsonTwp\LIS\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\24WaylandTwp\IntlFt\ParcelsPlus.shp.xml S:\Secure\Units\WaylandTwp\LIS\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\42MartinVillage\IntlFt\ParcelsPlus.shp.xml S:\Secure\Units\MartinVillage\LIS\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\44HopkinsVillage\IntlFt\ParcelsPlus.shp.xml S:\Secure\Units\HopkinsVillage\LIS\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\51AlleganCity\IntlFt\ParcelsPlus.shp.xml S:\Secure\Units\AlleganCity\LIS\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\52FennvilleCity\IntlFt\ParcelsPlus.shp.xml S:\Secure\Units\FennvilleCity\LIS\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\54OtsegoCity\IntlFt\ParcelsPlus.shp.xml S:\Secure\Units\OtsegoCity\LIS\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\55PlainwellCity\IntlFt\ParcelsPlus.shp.xml S:\Secure\Units\PlainwellCity\LIS\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\56WaylandCity\IntlFt\ParcelsPlus.shp.xml S:\Secure\Units\WaylandCity\LIS\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\57SaugatuckCity\IntlFt\ParcelsPlus.shp.xml S:\Secure\Units\SaugatuckCity\LIS\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\59DouglasCity\IntlFt\ParcelsPlus.shp.xml S:\Secure\Units\DouglasCity\LIS\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\01AlleganTwp\IntlFt\ParcelsPlus.sbx S:\Secure\Units\AlleganTwp\LIS\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\02CascoTwp\IntlFt\ParcelsPlus.sbx S:\Secure\Units\CascoTwp\LIS\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\03CheshireTwp\IntlFt\ParcelsPlus.sbx S:\Secure\Units\CheshireTwp\LIS\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\04ClydeTwp\IntlFt\ParcelsPlus.sbx S:\Secure\Units\ClydeTwp\LIS\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\05DorrTwp\IntlFt\ParcelsPlus.sbx S:\Secure\Units\DorrTwp\LIS\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\06FillmoreTwp\IntlFt\ParcelsPlus.sbx S:\Secure\Units\FillmoreTwp\LIS\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\07GangesTwp\IntlFt\ParcelsPlus.sbx S:\Secure\Units\GangesTwp\LIS\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\08GunPlainTwp\IntlFt\ParcelsPlus.sbx S:\Secure\Units\GunPlainTwp\LIS\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\09HeathTwp\IntlFt\ParcelsPlus.sbx S:\Secure\Units\HeathTwp\LIS\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\10HopkinsTwp\IntlFt\ParcelsPlus.sbx S:\Secure\Units\HopkinsTwp\LIS\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\11LaketownTwp\IntlFt\ParcelsPlus.sbx S:\Secure\Units\LaketownTwp\LIS\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\12LeeTwp\IntlFt\ParcelsPlus.sbx S:\Secure\Units\LeeTwp\LIS\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\13LeightonTwp\IntlFt\ParcelsPlus.sbx S:\Secure\Units\LeightonTwp\LIS\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\14ManliusTwp\IntlFt\ParcelsPlus.sbx S:\Secure\Units\ManliusTwp\LIS\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\15MartinTwp\IntlFt\ParcelsPlus.sbx S:\Secure\Units\MartinTwp\LIS\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\16MontereyTwp\IntlFt\ParcelsPlus.sbx S:\Secure\Units\MontereyTwp\LIS\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\17OtsegoTwp\IntlFt\ParcelsPlus.sbx S:\Secure\Units\OtsegoTwp\LIS\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\18OveriselTwp\IntlFt\ParcelsPlus.sbx S:\Secure\Units\OveriselTwp\LIS\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\19SalemTwp\IntlFt\ParcelsPlus.sbx S:\Secure\Units\SalemTwp\LIS\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\20SaugatuckTwp\IntlFt\ParcelsPlus.sbx S:\Secure\Units\SaugatuckTwp\LIS\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\21TrowbridgeTwp\IntlFt\ParcelsPlus.sbx S:\Secure\Units\TrowbridgeTwp\LIS\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\22ValleyTwp\IntlFt\ParcelsPlus.sbx S:\Secure\Units\ValleyTwp\LIS\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\23WatsonTwp\IntlFt\ParcelsPlus.sbx S:\Secure\Units\WatsonTwp\LIS\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\24WaylandTwp\IntlFt\ParcelsPlus.sbx S:\Secure\Units\WaylandTwp\LIS\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\42MartinVillage\IntlFt\ParcelsPlus.sbx S:\Secure\Units\MartinVillage\LIS\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\44HopkinsVillage\IntlFt\ParcelsPlus.sbx S:\Secure\Units\HopkinsVillage\LIS\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\51AlleganCity\IntlFt\ParcelsPlus.sbx S:\Secure\Units\AlleganCity\LIS\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\52FennvilleCity\IntlFt\ParcelsPlus.sbx S:\Secure\Units\FennvilleCity\LIS\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\54OtsegoCity\IntlFt\ParcelsPlus.sbx S:\Secure\Units\OtsegoCity\LIS\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\55PlainwellCity\IntlFt\ParcelsPlus.sbx S:\Secure\Units\PlainwellCity\LIS\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\56WaylandCity\IntlFt\ParcelsPlus.sbx S:\Secure\Units\WaylandCity\LIS\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\57SaugatuckCity\IntlFt\ParcelsPlus.sbx S:\Secure\Units\SaugatuckCity\LIS\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\59DouglasCity\IntlFt\ParcelsPlus.sbx S:\Secure\Units\DouglasCity\LIS\IntlFt\ParcelsPlus.sbx
