copy J:\Apps\Products\AccuGlobe\LocalUnits\build\01AlleganTwp\IntlFt\Parcels.cpg J:\data\Shapefiles\01AlleganTwp\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\01AlleganTwp\IntlFt\Parcels.dbf J:\data\Shapefiles\01AlleganTwp\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\01AlleganTwp\IntlFt\Parcels.prj J:\data\Shapefiles\01AlleganTwp\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\01AlleganTwp\IntlFt\Parcels.sbn J:\data\Shapefiles\01AlleganTwp\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\01AlleganTwp\IntlFt\Parcels.sbx J:\data\Shapefiles\01AlleganTwp\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\01AlleganTwp\IntlFt\Parcels.shp J:\data\Shapefiles\01AlleganTwp\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\01AlleganTwp\IntlFt\Parcels.shp.xml J:\data\Shapefiles\01AlleganTwp\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\01AlleganTwp\IntlFt\Parcels.shx J:\data\Shapefiles\01AlleganTwp\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\02CascoTwp\IntlFt\Parcels.cpg J:\data\Shapefiles\02CascoTwp\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\02CascoTwp\IntlFt\Parcels.dbf J:\data\Shapefiles\02CascoTwp\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\02CascoTwp\IntlFt\Parcels.prj J:\data\Shapefiles\02CascoTwp\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\02CascoTwp\IntlFt\Parcels.sbn J:\data\Shapefiles\02CascoTwp\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\02CascoTwp\IntlFt\Parcels.sbx J:\data\Shapefiles\02CascoTwp\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\02CascoTwp\IntlFt\Parcels.shp J:\data\Shapefiles\02CascoTwp\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\02CascoTwp\IntlFt\Parcels.shp.xml J:\data\Shapefiles\02CascoTwp\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\02CascoTwp\IntlFt\Parcels.shx J:\data\Shapefiles\02CascoTwp\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\03CheshireTwp\IntlFt\Parcels.cpg J:\data\Shapefiles\03CheshireTwp\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\03CheshireTwp\IntlFt\Parcels.dbf J:\data\Shapefiles\03CheshireTwp\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\03CheshireTwp\IntlFt\Parcels.prj J:\data\Shapefiles\03CheshireTwp\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\03CheshireTwp\IntlFt\Parcels.sbn J:\data\Shapefiles\03CheshireTwp\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\03CheshireTwp\IntlFt\Parcels.sbx J:\data\Shapefiles\03CheshireTwp\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\03CheshireTwp\IntlFt\Parcels.shp J:\data\Shapefiles\03CheshireTwp\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\03CheshireTwp\IntlFt\Parcels.shp.xml J:\data\Shapefiles\03CheshireTwp\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\03CheshireTwp\IntlFt\Parcels.shx J:\data\Shapefiles\03CheshireTwp\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\04ClydeTwp\IntlFt\Parcels.cpg J:\data\Shapefiles\04ClydeTwp\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\04ClydeTwp\IntlFt\Parcels.dbf J:\data\Shapefiles\04ClydeTwp\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\04ClydeTwp\IntlFt\Parcels.prj J:\data\Shapefiles\04ClydeTwp\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\04ClydeTwp\IntlFt\Parcels.sbn J:\data\Shapefiles\04ClydeTwp\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\04ClydeTwp\IntlFt\Parcels.sbx J:\data\Shapefiles\04ClydeTwp\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\04ClydeTwp\IntlFt\Parcels.shp J:\data\Shapefiles\04ClydeTwp\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\04ClydeTwp\IntlFt\Parcels.shp.xml J:\data\Shapefiles\04ClydeTwp\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\04ClydeTwp\IntlFt\Parcels.shx J:\data\Shapefiles\04ClydeTwp\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\05DorrTwp\IntlFt\Parcels.cpg J:\data\Shapefiles\05DorrTwp\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\05DorrTwp\IntlFt\Parcels.dbf J:\data\Shapefiles\05DorrTwp\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\05DorrTwp\IntlFt\Parcels.prj J:\data\Shapefiles\05DorrTwp\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\05DorrTwp\IntlFt\Parcels.sbn J:\data\Shapefiles\05DorrTwp\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\05DorrTwp\IntlFt\Parcels.sbx J:\data\Shapefiles\05DorrTwp\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\05DorrTwp\IntlFt\Parcels.shp J:\data\Shapefiles\05DorrTwp\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\05DorrTwp\IntlFt\Parcels.shp.xml J:\data\Shapefiles\05DorrTwp\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\05DorrTwp\IntlFt\Parcels.shx J:\data\Shapefiles\05DorrTwp\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\06FillmoreTwp\IntlFt\Parcels.cpg J:\data\Shapefiles\06FillmoreTwp\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\06FillmoreTwp\IntlFt\Parcels.dbf J:\data\Shapefiles\06FillmoreTwp\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\06FillmoreTwp\IntlFt\Parcels.prj J:\data\Shapefiles\06FillmoreTwp\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\06FillmoreTwp\IntlFt\Parcels.sbn J:\data\Shapefiles\06FillmoreTwp\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\06FillmoreTwp\IntlFt\Parcels.sbx J:\data\Shapefiles\06FillmoreTwp\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\06FillmoreTwp\IntlFt\Parcels.shp J:\data\Shapefiles\06FillmoreTwp\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\06FillmoreTwp\IntlFt\Parcels.shp.xml J:\data\Shapefiles\06FillmoreTwp\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\06FillmoreTwp\IntlFt\Parcels.shx J:\data\Shapefiles\06FillmoreTwp\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\07GangesTwp\IntlFt\Parcels.cpg J:\data\Shapefiles\07GangesTwp\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\07GangesTwp\IntlFt\Parcels.dbf J:\data\Shapefiles\07GangesTwp\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\07GangesTwp\IntlFt\Parcels.prj J:\data\Shapefiles\07GangesTwp\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\07GangesTwp\IntlFt\Parcels.sbn J:\data\Shapefiles\07GangesTwp\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\07GangesTwp\IntlFt\Parcels.sbx J:\data\Shapefiles\07GangesTwp\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\07GangesTwp\IntlFt\Parcels.shp J:\data\Shapefiles\07GangesTwp\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\07GangesTwp\IntlFt\Parcels.shp.xml J:\data\Shapefiles\07GangesTwp\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\07GangesTwp\IntlFt\Parcels.shx J:\data\Shapefiles\07GangesTwp\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\08GunPlainTwp\IntlFt\Parcels.cpg J:\data\Shapefiles\08GunPlainTwp\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\08GunPlainTwp\IntlFt\Parcels.dbf J:\data\Shapefiles\08GunPlainTwp\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\08GunPlainTwp\IntlFt\Parcels.prj J:\data\Shapefiles\08GunPlainTwp\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\08GunPlainTwp\IntlFt\Parcels.sbn J:\data\Shapefiles\08GunPlainTwp\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\08GunPlainTwp\IntlFt\Parcels.sbx J:\data\Shapefiles\08GunPlainTwp\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\08GunPlainTwp\IntlFt\Parcels.shp J:\data\Shapefiles\08GunPlainTwp\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\08GunPlainTwp\IntlFt\Parcels.shp.xml J:\data\Shapefiles\08GunPlainTwp\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\08GunPlainTwp\IntlFt\Parcels.shx J:\data\Shapefiles\08GunPlainTwp\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\09HeathTwp\IntlFt\Parcels.cpg J:\data\Shapefiles\09HeathTwp\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\09HeathTwp\IntlFt\Parcels.dbf J:\data\Shapefiles\09HeathTwp\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\09HeathTwp\IntlFt\Parcels.prj J:\data\Shapefiles\09HeathTwp\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\09HeathTwp\IntlFt\Parcels.sbn J:\data\Shapefiles\09HeathTwp\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\09HeathTwp\IntlFt\Parcels.sbx J:\data\Shapefiles\09HeathTwp\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\09HeathTwp\IntlFt\Parcels.shp J:\data\Shapefiles\09HeathTwp\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\09HeathTwp\IntlFt\Parcels.shp.xml J:\data\Shapefiles\09HeathTwp\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\09HeathTwp\IntlFt\Parcels.shx J:\data\Shapefiles\09HeathTwp\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\10HopkinsTwp\IntlFt\Parcels.cpg J:\data\Shapefiles\10HopkinsTwp\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\10HopkinsTwp\IntlFt\Parcels.dbf J:\data\Shapefiles\10HopkinsTwp\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\10HopkinsTwp\IntlFt\Parcels.prj J:\data\Shapefiles\10HopkinsTwp\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\10HopkinsTwp\IntlFt\Parcels.sbn J:\data\Shapefiles\10HopkinsTwp\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\10HopkinsTwp\IntlFt\Parcels.sbx J:\data\Shapefiles\10HopkinsTwp\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\10HopkinsTwp\IntlFt\Parcels.shp J:\data\Shapefiles\10HopkinsTwp\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\10HopkinsTwp\IntlFt\Parcels.shp.xml J:\data\Shapefiles\10HopkinsTwp\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\10HopkinsTwp\IntlFt\Parcels.shx J:\data\Shapefiles\10HopkinsTwp\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\11LaketownTwp\IntlFt\Parcels.cpg J:\data\Shapefiles\11LaketownTwp\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\11LaketownTwp\IntlFt\Parcels.dbf J:\data\Shapefiles\11LaketownTwp\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\11LaketownTwp\IntlFt\Parcels.prj J:\data\Shapefiles\11LaketownTwp\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\11LaketownTwp\IntlFt\Parcels.sbn J:\data\Shapefiles\11LaketownTwp\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\11LaketownTwp\IntlFt\Parcels.sbx J:\data\Shapefiles\11LaketownTwp\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\11LaketownTwp\IntlFt\Parcels.shp J:\data\Shapefiles\11LaketownTwp\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\11LaketownTwp\IntlFt\Parcels.shp.xml J:\data\Shapefiles\11LaketownTwp\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\11LaketownTwp\IntlFt\Parcels.shx J:\data\Shapefiles\11LaketownTwp\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\12LeeTwp\IntlFt\Parcels.cpg J:\data\Shapefiles\12LeeTwp\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\12LeeTwp\IntlFt\Parcels.dbf J:\data\Shapefiles\12LeeTwp\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\12LeeTwp\IntlFt\Parcels.prj J:\data\Shapefiles\12LeeTwp\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\12LeeTwp\IntlFt\Parcels.sbn J:\data\Shapefiles\12LeeTwp\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\12LeeTwp\IntlFt\Parcels.sbx J:\data\Shapefiles\12LeeTwp\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\12LeeTwp\IntlFt\Parcels.shp J:\data\Shapefiles\12LeeTwp\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\12LeeTwp\IntlFt\Parcels.shp.xml J:\data\Shapefiles\12LeeTwp\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\12LeeTwp\IntlFt\Parcels.shx J:\data\Shapefiles\12LeeTwp\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\13LeightonTwp\IntlFt\Parcels.cpg J:\data\Shapefiles\13LeightonTwp\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\13LeightonTwp\IntlFt\Parcels.dbf J:\data\Shapefiles\13LeightonTwp\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\13LeightonTwp\IntlFt\Parcels.prj J:\data\Shapefiles\13LeightonTwp\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\13LeightonTwp\IntlFt\Parcels.sbn J:\data\Shapefiles\13LeightonTwp\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\13LeightonTwp\IntlFt\Parcels.sbx J:\data\Shapefiles\13LeightonTwp\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\13LeightonTwp\IntlFt\Parcels.shp J:\data\Shapefiles\13LeightonTwp\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\13LeightonTwp\IntlFt\Parcels.shp.xml J:\data\Shapefiles\13LeightonTwp\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\13LeightonTwp\IntlFt\Parcels.shx J:\data\Shapefiles\13LeightonTwp\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\14ManliusTwp\IntlFt\Parcels.cpg J:\data\Shapefiles\14ManliusTwp\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\14ManliusTwp\IntlFt\Parcels.dbf J:\data\Shapefiles\14ManliusTwp\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\14ManliusTwp\IntlFt\Parcels.prj J:\data\Shapefiles\14ManliusTwp\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\14ManliusTwp\IntlFt\Parcels.sbn J:\data\Shapefiles\14ManliusTwp\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\14ManliusTwp\IntlFt\Parcels.sbx J:\data\Shapefiles\14ManliusTwp\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\14ManliusTwp\IntlFt\Parcels.shp J:\data\Shapefiles\14ManliusTwp\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\14ManliusTwp\IntlFt\Parcels.shp.xml J:\data\Shapefiles\14ManliusTwp\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\14ManliusTwp\IntlFt\Parcels.shx J:\data\Shapefiles\14ManliusTwp\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\15MartinTwp\IntlFt\Parcels.cpg J:\data\Shapefiles\15MartinTwp\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\15MartinTwp\IntlFt\Parcels.dbf J:\data\Shapefiles\15MartinTwp\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\15MartinTwp\IntlFt\Parcels.prj J:\data\Shapefiles\15MartinTwp\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\15MartinTwp\IntlFt\Parcels.sbn J:\data\Shapefiles\15MartinTwp\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\15MartinTwp\IntlFt\Parcels.sbx J:\data\Shapefiles\15MartinTwp\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\15MartinTwp\IntlFt\Parcels.shp J:\data\Shapefiles\15MartinTwp\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\15MartinTwp\IntlFt\Parcels.shp.xml J:\data\Shapefiles\15MartinTwp\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\15MartinTwp\IntlFt\Parcels.shx J:\data\Shapefiles\15MartinTwp\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\16MontereyTwp\IntlFt\Parcels.cpg J:\data\Shapefiles\16MontereyTwp\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\16MontereyTwp\IntlFt\Parcels.dbf J:\data\Shapefiles\16MontereyTwp\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\16MontereyTwp\IntlFt\Parcels.prj J:\data\Shapefiles\16MontereyTwp\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\16MontereyTwp\IntlFt\Parcels.sbn J:\data\Shapefiles\16MontereyTwp\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\16MontereyTwp\IntlFt\Parcels.sbx J:\data\Shapefiles\16MontereyTwp\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\16MontereyTwp\IntlFt\Parcels.shp J:\data\Shapefiles\16MontereyTwp\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\16MontereyTwp\IntlFt\Parcels.shp.xml J:\data\Shapefiles\16MontereyTwp\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\16MontereyTwp\IntlFt\Parcels.shx J:\data\Shapefiles\16MontereyTwp\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\17OtsegoTwp\IntlFt\Parcels.cpg J:\data\Shapefiles\17OtsegoTwp\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\17OtsegoTwp\IntlFt\Parcels.dbf J:\data\Shapefiles\17OtsegoTwp\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\17OtsegoTwp\IntlFt\Parcels.prj J:\data\Shapefiles\17OtsegoTwp\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\17OtsegoTwp\IntlFt\Parcels.sbn J:\data\Shapefiles\17OtsegoTwp\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\17OtsegoTwp\IntlFt\Parcels.sbx J:\data\Shapefiles\17OtsegoTwp\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\17OtsegoTwp\IntlFt\Parcels.shp J:\data\Shapefiles\17OtsegoTwp\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\17OtsegoTwp\IntlFt\Parcels.shp.xml J:\data\Shapefiles\17OtsegoTwp\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\17OtsegoTwp\IntlFt\Parcels.shx J:\data\Shapefiles\17OtsegoTwp\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\18OveriselTwp\IntlFt\Parcels.cpg J:\data\Shapefiles\18OveriselTwp\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\18OveriselTwp\IntlFt\Parcels.dbf J:\data\Shapefiles\18OveriselTwp\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\18OveriselTwp\IntlFt\Parcels.prj J:\data\Shapefiles\18OveriselTwp\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\18OveriselTwp\IntlFt\Parcels.sbn J:\data\Shapefiles\18OveriselTwp\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\18OveriselTwp\IntlFt\Parcels.sbx J:\data\Shapefiles\18OveriselTwp\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\18OveriselTwp\IntlFt\Parcels.shp J:\data\Shapefiles\18OveriselTwp\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\18OveriselTwp\IntlFt\Parcels.shp.xml J:\data\Shapefiles\18OveriselTwp\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\18OveriselTwp\IntlFt\Parcels.shx J:\data\Shapefiles\18OveriselTwp\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\19SalemTwp\IntlFt\Parcels.cpg J:\data\Shapefiles\19SalemTwp\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\19SalemTwp\IntlFt\Parcels.dbf J:\data\Shapefiles\19SalemTwp\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\19SalemTwp\IntlFt\Parcels.prj J:\data\Shapefiles\19SalemTwp\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\19SalemTwp\IntlFt\Parcels.sbn J:\data\Shapefiles\19SalemTwp\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\19SalemTwp\IntlFt\Parcels.sbx J:\data\Shapefiles\19SalemTwp\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\19SalemTwp\IntlFt\Parcels.shp J:\data\Shapefiles\19SalemTwp\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\19SalemTwp\IntlFt\Parcels.shp.xml J:\data\Shapefiles\19SalemTwp\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\19SalemTwp\IntlFt\Parcels.shx J:\data\Shapefiles\19SalemTwp\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\20SaugatuckTwp\IntlFt\Parcels.cpg J:\data\Shapefiles\20SaugatuckTwp\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\20SaugatuckTwp\IntlFt\Parcels.dbf J:\data\Shapefiles\20SaugatuckTwp\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\20SaugatuckTwp\IntlFt\Parcels.prj J:\data\Shapefiles\20SaugatuckTwp\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\20SaugatuckTwp\IntlFt\Parcels.sbn J:\data\Shapefiles\20SaugatuckTwp\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\20SaugatuckTwp\IntlFt\Parcels.sbx J:\data\Shapefiles\20SaugatuckTwp\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\20SaugatuckTwp\IntlFt\Parcels.shp J:\data\Shapefiles\20SaugatuckTwp\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\20SaugatuckTwp\IntlFt\Parcels.shp.xml J:\data\Shapefiles\20SaugatuckTwp\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\20SaugatuckTwp\IntlFt\Parcels.shx J:\data\Shapefiles\20SaugatuckTwp\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\21TrowbridgeTwp\IntlFt\Parcels.cpg J:\data\Shapefiles\21TrowbridgeTwp\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\21TrowbridgeTwp\IntlFt\Parcels.dbf J:\data\Shapefiles\21TrowbridgeTwp\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\21TrowbridgeTwp\IntlFt\Parcels.prj J:\data\Shapefiles\21TrowbridgeTwp\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\21TrowbridgeTwp\IntlFt\Parcels.sbn J:\data\Shapefiles\21TrowbridgeTwp\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\21TrowbridgeTwp\IntlFt\Parcels.sbx J:\data\Shapefiles\21TrowbridgeTwp\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\21TrowbridgeTwp\IntlFt\Parcels.shp J:\data\Shapefiles\21TrowbridgeTwp\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\21TrowbridgeTwp\IntlFt\Parcels.shp.xml J:\data\Shapefiles\21TrowbridgeTwp\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\21TrowbridgeTwp\IntlFt\Parcels.shx J:\data\Shapefiles\21TrowbridgeTwp\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\22ValleyTwp\IntlFt\Parcels.cpg J:\data\Shapefiles\22ValleyTwp\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\22ValleyTwp\IntlFt\Parcels.dbf J:\data\Shapefiles\22ValleyTwp\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\22ValleyTwp\IntlFt\Parcels.prj J:\data\Shapefiles\22ValleyTwp\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\22ValleyTwp\IntlFt\Parcels.sbn J:\data\Shapefiles\22ValleyTwp\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\22ValleyTwp\IntlFt\Parcels.sbx J:\data\Shapefiles\22ValleyTwp\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\22ValleyTwp\IntlFt\Parcels.shp J:\data\Shapefiles\22ValleyTwp\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\22ValleyTwp\IntlFt\Parcels.shp.xml J:\data\Shapefiles\22ValleyTwp\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\22ValleyTwp\IntlFt\Parcels.shx J:\data\Shapefiles\22ValleyTwp\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\23WatsonTwp\IntlFt\Parcels.cpg J:\data\Shapefiles\23WatsonTwp\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\23WatsonTwp\IntlFt\Parcels.dbf J:\data\Shapefiles\23WatsonTwp\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\23WatsonTwp\IntlFt\Parcels.prj J:\data\Shapefiles\23WatsonTwp\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\23WatsonTwp\IntlFt\Parcels.sbn J:\data\Shapefiles\23WatsonTwp\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\23WatsonTwp\IntlFt\Parcels.sbx J:\data\Shapefiles\23WatsonTwp\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\23WatsonTwp\IntlFt\Parcels.shp J:\data\Shapefiles\23WatsonTwp\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\23WatsonTwp\IntlFt\Parcels.shp.xml J:\data\Shapefiles\23WatsonTwp\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\23WatsonTwp\IntlFt\Parcels.shx J:\data\Shapefiles\23WatsonTwp\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\24WaylandTwp\IntlFt\Parcels.cpg J:\data\Shapefiles\24WaylandTwp\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\24WaylandTwp\IntlFt\Parcels.dbf J:\data\Shapefiles\24WaylandTwp\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\24WaylandTwp\IntlFt\Parcels.prj J:\data\Shapefiles\24WaylandTwp\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\24WaylandTwp\IntlFt\Parcels.sbn J:\data\Shapefiles\24WaylandTwp\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\24WaylandTwp\IntlFt\Parcels.sbx J:\data\Shapefiles\24WaylandTwp\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\24WaylandTwp\IntlFt\Parcels.shp J:\data\Shapefiles\24WaylandTwp\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\24WaylandTwp\IntlFt\Parcels.shp.xml J:\data\Shapefiles\24WaylandTwp\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\24WaylandTwp\IntlFt\Parcels.shx J:\data\Shapefiles\24WaylandTwp\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\42MartinVillage\IntlFt\Parcels.cpg J:\data\Shapefiles\42MartinVillage\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\42MartinVillage\IntlFt\Parcels.dbf J:\data\Shapefiles\42MartinVillage\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\42MartinVillage\IntlFt\Parcels.prj J:\data\Shapefiles\42MartinVillage\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\42MartinVillage\IntlFt\Parcels.sbn J:\data\Shapefiles\42MartinVillage\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\42MartinVillage\IntlFt\Parcels.sbx J:\data\Shapefiles\42MartinVillage\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\42MartinVillage\IntlFt\Parcels.shp J:\data\Shapefiles\42MartinVillage\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\42MartinVillage\IntlFt\Parcels.shp.xml J:\data\Shapefiles\42MartinVillage\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\42MartinVillage\IntlFt\Parcels.shx J:\data\Shapefiles\42MartinVillage\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\44HopkinsVillage\IntlFt\Parcels.cpg J:\data\Shapefiles\44HopkinsVillage\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\44HopkinsVillage\IntlFt\Parcels.dbf J:\data\Shapefiles\44HopkinsVillage\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\44HopkinsVillage\IntlFt\Parcels.prj J:\data\Shapefiles\44HopkinsVillage\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\44HopkinsVillage\IntlFt\Parcels.sbn J:\data\Shapefiles\44HopkinsVillage\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\44HopkinsVillage\IntlFt\Parcels.sbx J:\data\Shapefiles\44HopkinsVillage\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\44HopkinsVillage\IntlFt\Parcels.shp J:\data\Shapefiles\44HopkinsVillage\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\44HopkinsVillage\IntlFt\Parcels.shp.xml J:\data\Shapefiles\44HopkinsVillage\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\44HopkinsVillage\IntlFt\Parcels.shx J:\data\Shapefiles\44HopkinsVillage\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\51AlleganCity\IntlFt\Parcels.cpg J:\data\Shapefiles\51AlleganCity\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\51AlleganCity\IntlFt\Parcels.dbf J:\data\Shapefiles\51AlleganCity\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\51AlleganCity\IntlFt\Parcels.prj J:\data\Shapefiles\51AlleganCity\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\51AlleganCity\IntlFt\Parcels.sbn J:\data\Shapefiles\51AlleganCity\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\51AlleganCity\IntlFt\Parcels.sbx J:\data\Shapefiles\51AlleganCity\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\51AlleganCity\IntlFt\Parcels.shp J:\data\Shapefiles\51AlleganCity\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\51AlleganCity\IntlFt\Parcels.shp.xml J:\data\Shapefiles\51AlleganCity\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\51AlleganCity\IntlFt\Parcels.shx J:\data\Shapefiles\51AlleganCity\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\52FennvilleCity\IntlFt\Parcels.cpg J:\data\Shapefiles\52FennvilleCity\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\52FennvilleCity\IntlFt\Parcels.dbf J:\data\Shapefiles\52FennvilleCity\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\52FennvilleCity\IntlFt\Parcels.prj J:\data\Shapefiles\52FennvilleCity\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\52FennvilleCity\IntlFt\Parcels.sbn J:\data\Shapefiles\52FennvilleCity\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\52FennvilleCity\IntlFt\Parcels.sbx J:\data\Shapefiles\52FennvilleCity\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\52FennvilleCity\IntlFt\Parcels.shp J:\data\Shapefiles\52FennvilleCity\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\52FennvilleCity\IntlFt\Parcels.shp.xml J:\data\Shapefiles\52FennvilleCity\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\52FennvilleCity\IntlFt\Parcels.shx J:\data\Shapefiles\52FennvilleCity\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\54OtsegoCity\IntlFt\Parcels.cpg J:\data\Shapefiles\54OtsegoCity\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\54OtsegoCity\IntlFt\Parcels.dbf J:\data\Shapefiles\54OtsegoCity\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\54OtsegoCity\IntlFt\Parcels.prj J:\data\Shapefiles\54OtsegoCity\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\54OtsegoCity\IntlFt\Parcels.sbn J:\data\Shapefiles\54OtsegoCity\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\54OtsegoCity\IntlFt\Parcels.sbx J:\data\Shapefiles\54OtsegoCity\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\54OtsegoCity\IntlFt\Parcels.shp J:\data\Shapefiles\54OtsegoCity\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\54OtsegoCity\IntlFt\Parcels.shp.xml J:\data\Shapefiles\54OtsegoCity\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\54OtsegoCity\IntlFt\Parcels.shx J:\data\Shapefiles\54OtsegoCity\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\55PlainwellCity\IntlFt\Parcels.cpg J:\data\Shapefiles\55PlainwellCity\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\55PlainwellCity\IntlFt\Parcels.dbf J:\data\Shapefiles\55PlainwellCity\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\55PlainwellCity\IntlFt\Parcels.prj J:\data\Shapefiles\55PlainwellCity\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\55PlainwellCity\IntlFt\Parcels.sbn J:\data\Shapefiles\55PlainwellCity\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\55PlainwellCity\IntlFt\Parcels.sbx J:\data\Shapefiles\55PlainwellCity\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\55PlainwellCity\IntlFt\Parcels.shp J:\data\Shapefiles\55PlainwellCity\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\55PlainwellCity\IntlFt\Parcels.shp.xml J:\data\Shapefiles\55PlainwellCity\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\55PlainwellCity\IntlFt\Parcels.shx J:\data\Shapefiles\55PlainwellCity\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\56WaylandCity\IntlFt\Parcels.cpg J:\data\Shapefiles\56WaylandCity\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\56WaylandCity\IntlFt\Parcels.dbf J:\data\Shapefiles\56WaylandCity\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\56WaylandCity\IntlFt\Parcels.prj J:\data\Shapefiles\56WaylandCity\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\56WaylandCity\IntlFt\Parcels.sbn J:\data\Shapefiles\56WaylandCity\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\56WaylandCity\IntlFt\Parcels.sbx J:\data\Shapefiles\56WaylandCity\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\56WaylandCity\IntlFt\Parcels.shp J:\data\Shapefiles\56WaylandCity\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\56WaylandCity\IntlFt\Parcels.shp.xml J:\data\Shapefiles\56WaylandCity\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\56WaylandCity\IntlFt\Parcels.shx J:\data\Shapefiles\56WaylandCity\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\57SaugatuckCity\IntlFt\Parcels.cpg J:\data\Shapefiles\57SaugatuckCity\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\57SaugatuckCity\IntlFt\Parcels.dbf J:\data\Shapefiles\57SaugatuckCity\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\57SaugatuckCity\IntlFt\Parcels.prj J:\data\Shapefiles\57SaugatuckCity\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\57SaugatuckCity\IntlFt\Parcels.sbn J:\data\Shapefiles\57SaugatuckCity\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\57SaugatuckCity\IntlFt\Parcels.sbx J:\data\Shapefiles\57SaugatuckCity\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\57SaugatuckCity\IntlFt\Parcels.shp J:\data\Shapefiles\57SaugatuckCity\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\57SaugatuckCity\IntlFt\Parcels.shp.xml J:\data\Shapefiles\57SaugatuckCity\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\57SaugatuckCity\IntlFt\Parcels.shx J:\data\Shapefiles\57SaugatuckCity\IntlFt\Parcels.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\59DouglasCity\IntlFt\Parcels.cpg J:\data\Shapefiles\59DouglasCity\IntlFt\Parcels.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\59DouglasCity\IntlFt\Parcels.dbf J:\data\Shapefiles\59DouglasCity\IntlFt\Parcels.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\59DouglasCity\IntlFt\Parcels.prj J:\data\Shapefiles\59DouglasCity\IntlFt\Parcels.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\59DouglasCity\IntlFt\Parcels.sbn J:\data\Shapefiles\59DouglasCity\IntlFt\Parcels.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\59DouglasCity\IntlFt\Parcels.sbx J:\data\Shapefiles\59DouglasCity\IntlFt\Parcels.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\59DouglasCity\IntlFt\Parcels.shp J:\data\Shapefiles\59DouglasCity\IntlFt\Parcels.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\59DouglasCity\IntlFt\Parcels.shp.xml J:\data\Shapefiles\59DouglasCity\IntlFt\Parcels.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\59DouglasCity\IntlFt\Parcels.shx J:\data\Shapefiles\59DouglasCity\IntlFt\Parcels.shx


