copy J:\Apps\Products\AccuGlobe\LocalUnits\build\01AlleganTwp\IntlFt\ParcelsPlus.cpg J:\data\Shapefiles\01AlleganTwp\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\01AlleganTwp\IntlFt\ParcelsPlus.dbf J:\data\Shapefiles\01AlleganTwp\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\01AlleganTwp\IntlFt\ParcelsPlus.prj J:\data\Shapefiles\01AlleganTwp\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\01AlleganTwp\IntlFt\ParcelsPlus.sbn J:\data\Shapefiles\01AlleganTwp\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\01AlleganTwp\IntlFt\ParcelsPlus.sbx J:\data\Shapefiles\01AlleganTwp\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\01AlleganTwp\IntlFt\ParcelsPlus.shp J:\data\Shapefiles\01AlleganTwp\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\01AlleganTwp\IntlFt\ParcelsPlus.shp.xml J:\data\Shapefiles\01AlleganTwp\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\01AlleganTwp\IntlFt\ParcelsPlus.shx J:\data\Shapefiles\01AlleganTwp\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\02CascoTwp\IntlFt\ParcelsPlus.cpg J:\data\Shapefiles\02CascoTwp\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\02CascoTwp\IntlFt\ParcelsPlus.dbf J:\data\Shapefiles\02CascoTwp\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\02CascoTwp\IntlFt\ParcelsPlus.prj J:\data\Shapefiles\02CascoTwp\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\02CascoTwp\IntlFt\ParcelsPlus.sbn J:\data\Shapefiles\02CascoTwp\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\02CascoTwp\IntlFt\ParcelsPlus.sbx J:\data\Shapefiles\02CascoTwp\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\02CascoTwp\IntlFt\ParcelsPlus.shp J:\data\Shapefiles\02CascoTwp\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\02CascoTwp\IntlFt\ParcelsPlus.shp.xml J:\data\Shapefiles\02CascoTwp\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\02CascoTwp\IntlFt\ParcelsPlus.shx J:\data\Shapefiles\02CascoTwp\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\03CheshireTwp\IntlFt\ParcelsPlus.cpg J:\data\Shapefiles\03CheshireTwp\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\03CheshireTwp\IntlFt\ParcelsPlus.dbf J:\data\Shapefiles\03CheshireTwp\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\03CheshireTwp\IntlFt\ParcelsPlus.prj J:\data\Shapefiles\03CheshireTwp\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\03CheshireTwp\IntlFt\ParcelsPlus.sbn J:\data\Shapefiles\03CheshireTwp\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\03CheshireTwp\IntlFt\ParcelsPlus.sbx J:\data\Shapefiles\03CheshireTwp\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\03CheshireTwp\IntlFt\ParcelsPlus.shp J:\data\Shapefiles\03CheshireTwp\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\03CheshireTwp\IntlFt\ParcelsPlus.shp.xml J:\data\Shapefiles\03CheshireTwp\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\03CheshireTwp\IntlFt\ParcelsPlus.shx J:\data\Shapefiles\03CheshireTwp\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\04ClydeTwp\IntlFt\ParcelsPlus.cpg J:\data\Shapefiles\04ClydeTwp\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\04ClydeTwp\IntlFt\ParcelsPlus.dbf J:\data\Shapefiles\04ClydeTwp\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\04ClydeTwp\IntlFt\ParcelsPlus.prj J:\data\Shapefiles\04ClydeTwp\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\04ClydeTwp\IntlFt\ParcelsPlus.sbn J:\data\Shapefiles\04ClydeTwp\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\04ClydeTwp\IntlFt\ParcelsPlus.sbx J:\data\Shapefiles\04ClydeTwp\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\04ClydeTwp\IntlFt\ParcelsPlus.shp J:\data\Shapefiles\04ClydeTwp\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\04ClydeTwp\IntlFt\ParcelsPlus.shp.xml J:\data\Shapefiles\04ClydeTwp\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\04ClydeTwp\IntlFt\ParcelsPlus.shx J:\data\Shapefiles\04ClydeTwp\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\05DorrTwp\IntlFt\ParcelsPlus.cpg J:\data\Shapefiles\05DorrTwp\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\05DorrTwp\IntlFt\ParcelsPlus.dbf J:\data\Shapefiles\05DorrTwp\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\05DorrTwp\IntlFt\ParcelsPlus.prj J:\data\Shapefiles\05DorrTwp\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\05DorrTwp\IntlFt\ParcelsPlus.sbn J:\data\Shapefiles\05DorrTwp\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\05DorrTwp\IntlFt\ParcelsPlus.sbx J:\data\Shapefiles\05DorrTwp\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\05DorrTwp\IntlFt\ParcelsPlus.shp J:\data\Shapefiles\05DorrTwp\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\05DorrTwp\IntlFt\ParcelsPlus.shp.xml J:\data\Shapefiles\05DorrTwp\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\05DorrTwp\IntlFt\ParcelsPlus.shx J:\data\Shapefiles\05DorrTwp\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\06FillmoreTwp\IntlFt\ParcelsPlus.cpg J:\data\Shapefiles\06FillmoreTwp\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\06FillmoreTwp\IntlFt\ParcelsPlus.dbf J:\data\Shapefiles\06FillmoreTwp\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\06FillmoreTwp\IntlFt\ParcelsPlus.prj J:\data\Shapefiles\06FillmoreTwp\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\06FillmoreTwp\IntlFt\ParcelsPlus.sbn J:\data\Shapefiles\06FillmoreTwp\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\06FillmoreTwp\IntlFt\ParcelsPlus.sbx J:\data\Shapefiles\06FillmoreTwp\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\06FillmoreTwp\IntlFt\ParcelsPlus.shp J:\data\Shapefiles\06FillmoreTwp\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\06FillmoreTwp\IntlFt\ParcelsPlus.shp.xml J:\data\Shapefiles\06FillmoreTwp\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\06FillmoreTwp\IntlFt\ParcelsPlus.shx J:\data\Shapefiles\06FillmoreTwp\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\07GangesTwp\IntlFt\ParcelsPlus.cpg J:\data\Shapefiles\07GangesTwp\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\07GangesTwp\IntlFt\ParcelsPlus.dbf J:\data\Shapefiles\07GangesTwp\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\07GangesTwp\IntlFt\ParcelsPlus.prj J:\data\Shapefiles\07GangesTwp\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\07GangesTwp\IntlFt\ParcelsPlus.sbn J:\data\Shapefiles\07GangesTwp\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\07GangesTwp\IntlFt\ParcelsPlus.sbx J:\data\Shapefiles\07GangesTwp\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\07GangesTwp\IntlFt\ParcelsPlus.shp J:\data\Shapefiles\07GangesTwp\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\07GangesTwp\IntlFt\ParcelsPlus.shp.xml J:\data\Shapefiles\07GangesTwp\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\07GangesTwp\IntlFt\ParcelsPlus.shx J:\data\Shapefiles\07GangesTwp\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\08GunPlainTwp\IntlFt\ParcelsPlus.cpg J:\data\Shapefiles\08GunPlainTwp\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\08GunPlainTwp\IntlFt\ParcelsPlus.dbf J:\data\Shapefiles\08GunPlainTwp\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\08GunPlainTwp\IntlFt\ParcelsPlus.prj J:\data\Shapefiles\08GunPlainTwp\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\08GunPlainTwp\IntlFt\ParcelsPlus.sbn J:\data\Shapefiles\08GunPlainTwp\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\08GunPlainTwp\IntlFt\ParcelsPlus.sbx J:\data\Shapefiles\08GunPlainTwp\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\08GunPlainTwp\IntlFt\ParcelsPlus.shp J:\data\Shapefiles\08GunPlainTwp\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\08GunPlainTwp\IntlFt\ParcelsPlus.shp.xml J:\data\Shapefiles\08GunPlainTwp\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\08GunPlainTwp\IntlFt\ParcelsPlus.shx J:\data\Shapefiles\08GunPlainTwp\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\09HeathTwp\IntlFt\ParcelsPlus.cpg J:\data\Shapefiles\09HeathTwp\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\09HeathTwp\IntlFt\ParcelsPlus.dbf J:\data\Shapefiles\09HeathTwp\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\09HeathTwp\IntlFt\ParcelsPlus.prj J:\data\Shapefiles\09HeathTwp\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\09HeathTwp\IntlFt\ParcelsPlus.sbn J:\data\Shapefiles\09HeathTwp\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\09HeathTwp\IntlFt\ParcelsPlus.sbx J:\data\Shapefiles\09HeathTwp\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\09HeathTwp\IntlFt\ParcelsPlus.shp J:\data\Shapefiles\09HeathTwp\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\09HeathTwp\IntlFt\ParcelsPlus.shp.xml J:\data\Shapefiles\09HeathTwp\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\09HeathTwp\IntlFt\ParcelsPlus.shx J:\data\Shapefiles\09HeathTwp\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\10HopkinsTwp\IntlFt\ParcelsPlus.cpg J:\data\Shapefiles\10HopkinsTwp\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\10HopkinsTwp\IntlFt\ParcelsPlus.dbf J:\data\Shapefiles\10HopkinsTwp\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\10HopkinsTwp\IntlFt\ParcelsPlus.prj J:\data\Shapefiles\10HopkinsTwp\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\10HopkinsTwp\IntlFt\ParcelsPlus.sbn J:\data\Shapefiles\10HopkinsTwp\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\10HopkinsTwp\IntlFt\ParcelsPlus.sbx J:\data\Shapefiles\10HopkinsTwp\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\10HopkinsTwp\IntlFt\ParcelsPlus.shp J:\data\Shapefiles\10HopkinsTwp\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\10HopkinsTwp\IntlFt\ParcelsPlus.shp.xml J:\data\Shapefiles\10HopkinsTwp\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\10HopkinsTwp\IntlFt\ParcelsPlus.shx J:\data\Shapefiles\10HopkinsTwp\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\11LaketownTwp\IntlFt\ParcelsPlus.cpg J:\data\Shapefiles\11LaketownTwp\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\11LaketownTwp\IntlFt\ParcelsPlus.dbf J:\data\Shapefiles\11LaketownTwp\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\11LaketownTwp\IntlFt\ParcelsPlus.prj J:\data\Shapefiles\11LaketownTwp\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\11LaketownTwp\IntlFt\ParcelsPlus.sbn J:\data\Shapefiles\11LaketownTwp\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\11LaketownTwp\IntlFt\ParcelsPlus.sbx J:\data\Shapefiles\11LaketownTwp\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\11LaketownTwp\IntlFt\ParcelsPlus.shp J:\data\Shapefiles\11LaketownTwp\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\11LaketownTwp\IntlFt\ParcelsPlus.shp.xml J:\data\Shapefiles\11LaketownTwp\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\11LaketownTwp\IntlFt\ParcelsPlus.shx J:\data\Shapefiles\11LaketownTwp\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\12LeeTwp\IntlFt\ParcelsPlus.cpg J:\data\Shapefiles\12LeeTwp\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\12LeeTwp\IntlFt\ParcelsPlus.dbf J:\data\Shapefiles\12LeeTwp\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\12LeeTwp\IntlFt\ParcelsPlus.prj J:\data\Shapefiles\12LeeTwp\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\12LeeTwp\IntlFt\ParcelsPlus.sbn J:\data\Shapefiles\12LeeTwp\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\12LeeTwp\IntlFt\ParcelsPlus.sbx J:\data\Shapefiles\12LeeTwp\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\12LeeTwp\IntlFt\ParcelsPlus.shp J:\data\Shapefiles\12LeeTwp\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\12LeeTwp\IntlFt\ParcelsPlus.shp.xml J:\data\Shapefiles\12LeeTwp\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\12LeeTwp\IntlFt\ParcelsPlus.shx J:\data\Shapefiles\12LeeTwp\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\13LeightonTwp\IntlFt\ParcelsPlus.cpg J:\data\Shapefiles\13LeightonTwp\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\13LeightonTwp\IntlFt\ParcelsPlus.dbf J:\data\Shapefiles\13LeightonTwp\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\13LeightonTwp\IntlFt\ParcelsPlus.prj J:\data\Shapefiles\13LeightonTwp\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\13LeightonTwp\IntlFt\ParcelsPlus.sbn J:\data\Shapefiles\13LeightonTwp\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\13LeightonTwp\IntlFt\ParcelsPlus.sbx J:\data\Shapefiles\13LeightonTwp\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\13LeightonTwp\IntlFt\ParcelsPlus.shp J:\data\Shapefiles\13LeightonTwp\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\13LeightonTwp\IntlFt\ParcelsPlus.shp.xml J:\data\Shapefiles\13LeightonTwp\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\13LeightonTwp\IntlFt\ParcelsPlus.shx J:\data\Shapefiles\13LeightonTwp\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\14ManliusTwp\IntlFt\ParcelsPlus.cpg J:\data\Shapefiles\14ManliusTwp\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\14ManliusTwp\IntlFt\ParcelsPlus.dbf J:\data\Shapefiles\14ManliusTwp\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\14ManliusTwp\IntlFt\ParcelsPlus.prj J:\data\Shapefiles\14ManliusTwp\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\14ManliusTwp\IntlFt\ParcelsPlus.sbn J:\data\Shapefiles\14ManliusTwp\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\14ManliusTwp\IntlFt\ParcelsPlus.sbx J:\data\Shapefiles\14ManliusTwp\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\14ManliusTwp\IntlFt\ParcelsPlus.shp J:\data\Shapefiles\14ManliusTwp\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\14ManliusTwp\IntlFt\ParcelsPlus.shp.xml J:\data\Shapefiles\14ManliusTwp\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\14ManliusTwp\IntlFt\ParcelsPlus.shx J:\data\Shapefiles\14ManliusTwp\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\15MartinTwp\IntlFt\ParcelsPlus.cpg J:\data\Shapefiles\15MartinTwp\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\15MartinTwp\IntlFt\ParcelsPlus.dbf J:\data\Shapefiles\15MartinTwp\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\15MartinTwp\IntlFt\ParcelsPlus.prj J:\data\Shapefiles\15MartinTwp\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\15MartinTwp\IntlFt\ParcelsPlus.sbn J:\data\Shapefiles\15MartinTwp\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\15MartinTwp\IntlFt\ParcelsPlus.sbx J:\data\Shapefiles\15MartinTwp\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\15MartinTwp\IntlFt\ParcelsPlus.shp J:\data\Shapefiles\15MartinTwp\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\15MartinTwp\IntlFt\ParcelsPlus.shp.xml J:\data\Shapefiles\15MartinTwp\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\15MartinTwp\IntlFt\ParcelsPlus.shx J:\data\Shapefiles\15MartinTwp\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\16MontereyTwp\IntlFt\ParcelsPlus.cpg J:\data\Shapefiles\16MontereyTwp\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\16MontereyTwp\IntlFt\ParcelsPlus.dbf J:\data\Shapefiles\16MontereyTwp\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\16MontereyTwp\IntlFt\ParcelsPlus.prj J:\data\Shapefiles\16MontereyTwp\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\16MontereyTwp\IntlFt\ParcelsPlus.sbn J:\data\Shapefiles\16MontereyTwp\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\16MontereyTwp\IntlFt\ParcelsPlus.sbx J:\data\Shapefiles\16MontereyTwp\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\16MontereyTwp\IntlFt\ParcelsPlus.shp J:\data\Shapefiles\16MontereyTwp\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\16MontereyTwp\IntlFt\ParcelsPlus.shp.xml J:\data\Shapefiles\16MontereyTwp\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\16MontereyTwp\IntlFt\ParcelsPlus.shx J:\data\Shapefiles\16MontereyTwp\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\17OtsegoTwp\IntlFt\ParcelsPlus.cpg J:\data\Shapefiles\17OtsegoTwp\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\17OtsegoTwp\IntlFt\ParcelsPlus.dbf J:\data\Shapefiles\17OtsegoTwp\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\17OtsegoTwp\IntlFt\ParcelsPlus.prj J:\data\Shapefiles\17OtsegoTwp\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\17OtsegoTwp\IntlFt\ParcelsPlus.sbn J:\data\Shapefiles\17OtsegoTwp\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\17OtsegoTwp\IntlFt\ParcelsPlus.sbx J:\data\Shapefiles\17OtsegoTwp\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\17OtsegoTwp\IntlFt\ParcelsPlus.shp J:\data\Shapefiles\17OtsegoTwp\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\17OtsegoTwp\IntlFt\ParcelsPlus.shp.xml J:\data\Shapefiles\17OtsegoTwp\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\17OtsegoTwp\IntlFt\ParcelsPlus.shx J:\data\Shapefiles\17OtsegoTwp\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\18OveriselTwp\IntlFt\ParcelsPlus.cpg J:\data\Shapefiles\18OveriselTwp\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\18OveriselTwp\IntlFt\ParcelsPlus.dbf J:\data\Shapefiles\18OveriselTwp\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\18OveriselTwp\IntlFt\ParcelsPlus.prj J:\data\Shapefiles\18OveriselTwp\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\18OveriselTwp\IntlFt\ParcelsPlus.sbn J:\data\Shapefiles\18OveriselTwp\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\18OveriselTwp\IntlFt\ParcelsPlus.sbx J:\data\Shapefiles\18OveriselTwp\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\18OveriselTwp\IntlFt\ParcelsPlus.shp J:\data\Shapefiles\18OveriselTwp\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\18OveriselTwp\IntlFt\ParcelsPlus.shp.xml J:\data\Shapefiles\18OveriselTwp\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\18OveriselTwp\IntlFt\ParcelsPlus.shx J:\data\Shapefiles\18OveriselTwp\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\19SalemTwp\IntlFt\ParcelsPlus.cpg J:\data\Shapefiles\19SalemTwp\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\19SalemTwp\IntlFt\ParcelsPlus.dbf J:\data\Shapefiles\19SalemTwp\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\19SalemTwp\IntlFt\ParcelsPlus.prj J:\data\Shapefiles\19SalemTwp\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\19SalemTwp\IntlFt\ParcelsPlus.sbn J:\data\Shapefiles\19SalemTwp\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\19SalemTwp\IntlFt\ParcelsPlus.sbx J:\data\Shapefiles\19SalemTwp\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\19SalemTwp\IntlFt\ParcelsPlus.shp J:\data\Shapefiles\19SalemTwp\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\19SalemTwp\IntlFt\ParcelsPlus.shp.xml J:\data\Shapefiles\19SalemTwp\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\19SalemTwp\IntlFt\ParcelsPlus.shx J:\data\Shapefiles\19SalemTwp\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\20SaugatuckTwp\IntlFt\ParcelsPlus.cpg J:\data\Shapefiles\20SaugatuckTwp\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\20SaugatuckTwp\IntlFt\ParcelsPlus.dbf J:\data\Shapefiles\20SaugatuckTwp\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\20SaugatuckTwp\IntlFt\ParcelsPlus.prj J:\data\Shapefiles\20SaugatuckTwp\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\20SaugatuckTwp\IntlFt\ParcelsPlus.sbn J:\data\Shapefiles\20SaugatuckTwp\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\20SaugatuckTwp\IntlFt\ParcelsPlus.sbx J:\data\Shapefiles\20SaugatuckTwp\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\20SaugatuckTwp\IntlFt\ParcelsPlus.shp J:\data\Shapefiles\20SaugatuckTwp\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\20SaugatuckTwp\IntlFt\ParcelsPlus.shp.xml J:\data\Shapefiles\20SaugatuckTwp\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\20SaugatuckTwp\IntlFt\ParcelsPlus.shx J:\data\Shapefiles\20SaugatuckTwp\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\21TrowbridgeTwp\IntlFt\ParcelsPlus.cpg J:\data\Shapefiles\21TrowbridgeTwp\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\21TrowbridgeTwp\IntlFt\ParcelsPlus.dbf J:\data\Shapefiles\21TrowbridgeTwp\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\21TrowbridgeTwp\IntlFt\ParcelsPlus.prj J:\data\Shapefiles\21TrowbridgeTwp\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\21TrowbridgeTwp\IntlFt\ParcelsPlus.sbn J:\data\Shapefiles\21TrowbridgeTwp\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\21TrowbridgeTwp\IntlFt\ParcelsPlus.sbx J:\data\Shapefiles\21TrowbridgeTwp\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\21TrowbridgeTwp\IntlFt\ParcelsPlus.shp J:\data\Shapefiles\21TrowbridgeTwp\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\21TrowbridgeTwp\IntlFt\ParcelsPlus.shp.xml J:\data\Shapefiles\21TrowbridgeTwp\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\21TrowbridgeTwp\IntlFt\ParcelsPlus.shx J:\data\Shapefiles\21TrowbridgeTwp\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\22ValleyTwp\IntlFt\ParcelsPlus.cpg J:\data\Shapefiles\22ValleyTwp\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\22ValleyTwp\IntlFt\ParcelsPlus.dbf J:\data\Shapefiles\22ValleyTwp\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\22ValleyTwp\IntlFt\ParcelsPlus.prj J:\data\Shapefiles\22ValleyTwp\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\22ValleyTwp\IntlFt\ParcelsPlus.sbn J:\data\Shapefiles\22ValleyTwp\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\22ValleyTwp\IntlFt\ParcelsPlus.sbx J:\data\Shapefiles\22ValleyTwp\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\22ValleyTwp\IntlFt\ParcelsPlus.shp J:\data\Shapefiles\22ValleyTwp\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\22ValleyTwp\IntlFt\ParcelsPlus.shp.xml J:\data\Shapefiles\22ValleyTwp\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\22ValleyTwp\IntlFt\ParcelsPlus.shx J:\data\Shapefiles\22ValleyTwp\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\23WatsonTwp\IntlFt\ParcelsPlus.cpg J:\data\Shapefiles\23WatsonTwp\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\23WatsonTwp\IntlFt\ParcelsPlus.dbf J:\data\Shapefiles\23WatsonTwp\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\23WatsonTwp\IntlFt\ParcelsPlus.prj J:\data\Shapefiles\23WatsonTwp\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\23WatsonTwp\IntlFt\ParcelsPlus.sbn J:\data\Shapefiles\23WatsonTwp\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\23WatsonTwp\IntlFt\ParcelsPlus.sbx J:\data\Shapefiles\23WatsonTwp\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\23WatsonTwp\IntlFt\ParcelsPlus.shp J:\data\Shapefiles\23WatsonTwp\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\23WatsonTwp\IntlFt\ParcelsPlus.shp.xml J:\data\Shapefiles\23WatsonTwp\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\23WatsonTwp\IntlFt\ParcelsPlus.shx J:\data\Shapefiles\23WatsonTwp\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\24WaylandTwp\IntlFt\ParcelsPlus.cpg J:\data\Shapefiles\24WaylandTwp\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\24WaylandTwp\IntlFt\ParcelsPlus.dbf J:\data\Shapefiles\24WaylandTwp\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\24WaylandTwp\IntlFt\ParcelsPlus.prj J:\data\Shapefiles\24WaylandTwp\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\24WaylandTwp\IntlFt\ParcelsPlus.sbn J:\data\Shapefiles\24WaylandTwp\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\24WaylandTwp\IntlFt\ParcelsPlus.sbx J:\data\Shapefiles\24WaylandTwp\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\24WaylandTwp\IntlFt\ParcelsPlus.shp J:\data\Shapefiles\24WaylandTwp\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\24WaylandTwp\IntlFt\ParcelsPlus.shp.xml J:\data\Shapefiles\24WaylandTwp\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\24WaylandTwp\IntlFt\ParcelsPlus.shx J:\data\Shapefiles\24WaylandTwp\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\42MartinVillage\IntlFt\ParcelsPlus.cpg J:\data\Shapefiles\42MartinVillage\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\42MartinVillage\IntlFt\ParcelsPlus.dbf J:\data\Shapefiles\42MartinVillage\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\42MartinVillage\IntlFt\ParcelsPlus.prj J:\data\Shapefiles\42MartinVillage\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\42MartinVillage\IntlFt\ParcelsPlus.sbn J:\data\Shapefiles\42MartinVillage\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\42MartinVillage\IntlFt\ParcelsPlus.sbx J:\data\Shapefiles\42MartinVillage\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\42MartinVillage\IntlFt\ParcelsPlus.shp J:\data\Shapefiles\42MartinVillage\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\42MartinVillage\IntlFt\ParcelsPlus.shp.xml J:\data\Shapefiles\42MartinVillage\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\42MartinVillage\IntlFt\ParcelsPlus.shx J:\data\Shapefiles\42MartinVillage\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\44HopkinsVillage\IntlFt\ParcelsPlus.cpg J:\data\Shapefiles\44HopkinsVillage\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\44HopkinsVillage\IntlFt\ParcelsPlus.dbf J:\data\Shapefiles\44HopkinsVillage\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\44HopkinsVillage\IntlFt\ParcelsPlus.prj J:\data\Shapefiles\44HopkinsVillage\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\44HopkinsVillage\IntlFt\ParcelsPlus.sbn J:\data\Shapefiles\44HopkinsVillage\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\44HopkinsVillage\IntlFt\ParcelsPlus.sbx J:\data\Shapefiles\44HopkinsVillage\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\44HopkinsVillage\IntlFt\ParcelsPlus.shp J:\data\Shapefiles\44HopkinsVillage\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\44HopkinsVillage\IntlFt\ParcelsPlus.shp.xml J:\data\Shapefiles\44HopkinsVillage\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\44HopkinsVillage\IntlFt\ParcelsPlus.shx J:\data\Shapefiles\44HopkinsVillage\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\51AlleganCity\IntlFt\ParcelsPlus.cpg J:\data\Shapefiles\51AlleganCity\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\51AlleganCity\IntlFt\ParcelsPlus.dbf J:\data\Shapefiles\51AlleganCity\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\51AlleganCity\IntlFt\ParcelsPlus.prj J:\data\Shapefiles\51AlleganCity\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\51AlleganCity\IntlFt\ParcelsPlus.sbn J:\data\Shapefiles\51AlleganCity\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\51AlleganCity\IntlFt\ParcelsPlus.sbx J:\data\Shapefiles\51AlleganCity\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\51AlleganCity\IntlFt\ParcelsPlus.shp J:\data\Shapefiles\51AlleganCity\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\51AlleganCity\IntlFt\ParcelsPlus.shp.xml J:\data\Shapefiles\51AlleganCity\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\51AlleganCity\IntlFt\ParcelsPlus.shx J:\data\Shapefiles\51AlleganCity\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\52FennvilleCity\IntlFt\ParcelsPlus.cpg J:\data\Shapefiles\52FennvilleCity\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\52FennvilleCity\IntlFt\ParcelsPlus.dbf J:\data\Shapefiles\52FennvilleCity\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\52FennvilleCity\IntlFt\ParcelsPlus.prj J:\data\Shapefiles\52FennvilleCity\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\52FennvilleCity\IntlFt\ParcelsPlus.sbn J:\data\Shapefiles\52FennvilleCity\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\52FennvilleCity\IntlFt\ParcelsPlus.sbx J:\data\Shapefiles\52FennvilleCity\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\52FennvilleCity\IntlFt\ParcelsPlus.shp J:\data\Shapefiles\52FennvilleCity\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\52FennvilleCity\IntlFt\ParcelsPlus.shp.xml J:\data\Shapefiles\52FennvilleCity\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\52FennvilleCity\IntlFt\ParcelsPlus.shx J:\data\Shapefiles\52FennvilleCity\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\54OtsegoCity\IntlFt\ParcelsPlus.cpg J:\data\Shapefiles\54OtsegoCity\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\54OtsegoCity\IntlFt\ParcelsPlus.dbf J:\data\Shapefiles\54OtsegoCity\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\54OtsegoCity\IntlFt\ParcelsPlus.prj J:\data\Shapefiles\54OtsegoCity\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\54OtsegoCity\IntlFt\ParcelsPlus.sbn J:\data\Shapefiles\54OtsegoCity\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\54OtsegoCity\IntlFt\ParcelsPlus.sbx J:\data\Shapefiles\54OtsegoCity\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\54OtsegoCity\IntlFt\ParcelsPlus.shp J:\data\Shapefiles\54OtsegoCity\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\54OtsegoCity\IntlFt\ParcelsPlus.shp.xml J:\data\Shapefiles\54OtsegoCity\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\54OtsegoCity\IntlFt\ParcelsPlus.shx J:\data\Shapefiles\54OtsegoCity\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\55PlainwellCity\IntlFt\ParcelsPlus.cpg J:\data\Shapefiles\55PlainwellCity\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\55PlainwellCity\IntlFt\ParcelsPlus.dbf J:\data\Shapefiles\55PlainwellCity\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\55PlainwellCity\IntlFt\ParcelsPlus.prj J:\data\Shapefiles\55PlainwellCity\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\55PlainwellCity\IntlFt\ParcelsPlus.sbn J:\data\Shapefiles\55PlainwellCity\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\55PlainwellCity\IntlFt\ParcelsPlus.sbx J:\data\Shapefiles\55PlainwellCity\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\55PlainwellCity\IntlFt\ParcelsPlus.shp J:\data\Shapefiles\55PlainwellCity\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\55PlainwellCity\IntlFt\ParcelsPlus.shp.xml J:\data\Shapefiles\55PlainwellCity\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\55PlainwellCity\IntlFt\ParcelsPlus.shx J:\data\Shapefiles\55PlainwellCity\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\56WaylandCity\IntlFt\ParcelsPlus.cpg J:\data\Shapefiles\56WaylandCity\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\56WaylandCity\IntlFt\ParcelsPlus.dbf J:\data\Shapefiles\56WaylandCity\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\56WaylandCity\IntlFt\ParcelsPlus.prj J:\data\Shapefiles\56WaylandCity\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\56WaylandCity\IntlFt\ParcelsPlus.sbn J:\data\Shapefiles\56WaylandCity\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\56WaylandCity\IntlFt\ParcelsPlus.sbx J:\data\Shapefiles\56WaylandCity\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\56WaylandCity\IntlFt\ParcelsPlus.shp J:\data\Shapefiles\56WaylandCity\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\56WaylandCity\IntlFt\ParcelsPlus.shp.xml J:\data\Shapefiles\56WaylandCity\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\56WaylandCity\IntlFt\ParcelsPlus.shx J:\data\Shapefiles\56WaylandCity\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\57SaugatuckCity\IntlFt\ParcelsPlus.cpg J:\data\Shapefiles\57SaugatuckCity\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\57SaugatuckCity\IntlFt\ParcelsPlus.dbf J:\data\Shapefiles\57SaugatuckCity\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\57SaugatuckCity\IntlFt\ParcelsPlus.prj J:\data\Shapefiles\57SaugatuckCity\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\57SaugatuckCity\IntlFt\ParcelsPlus.sbn J:\data\Shapefiles\57SaugatuckCity\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\57SaugatuckCity\IntlFt\ParcelsPlus.sbx J:\data\Shapefiles\57SaugatuckCity\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\57SaugatuckCity\IntlFt\ParcelsPlus.shp J:\data\Shapefiles\57SaugatuckCity\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\57SaugatuckCity\IntlFt\ParcelsPlus.shp.xml J:\data\Shapefiles\57SaugatuckCity\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\57SaugatuckCity\IntlFt\ParcelsPlus.shx J:\data\Shapefiles\57SaugatuckCity\IntlFt\ParcelsPlus.shx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\59DouglasCity\IntlFt\ParcelsPlus.cpg J:\data\Shapefiles\59DouglasCity\IntlFt\ParcelsPlus.cpg 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\59DouglasCity\IntlFt\ParcelsPlus.dbf J:\data\Shapefiles\59DouglasCity\IntlFt\ParcelsPlus.dbf
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\59DouglasCity\IntlFt\ParcelsPlus.prj J:\data\Shapefiles\59DouglasCity\IntlFt\ParcelsPlus.prj
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\59DouglasCity\IntlFt\ParcelsPlus.sbn J:\data\Shapefiles\59DouglasCity\IntlFt\ParcelsPlus.sbn 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\59DouglasCity\IntlFt\ParcelsPlus.sbx J:\data\Shapefiles\59DouglasCity\IntlFt\ParcelsPlus.sbx
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\59DouglasCity\IntlFt\ParcelsPlus.shp J:\data\Shapefiles\59DouglasCity\IntlFt\ParcelsPlus.shp 
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\59DouglasCity\IntlFt\ParcelsPlus.shp.xml J:\data\Shapefiles\59DouglasCity\IntlFt\ParcelsPlus.shp.xml
copy J:\Apps\Products\AccuGlobe\LocalUnits\build\59DouglasCity\IntlFt\ParcelsPlus.shx J:\data\Shapefiles\59DouglasCity\IntlFt\ParcelsPlus.shx


